const labels: Record<string, string> = {
  'hip flexors': 'Сгибатели бедра', obliques: 'Косые мышцы живота', core: 'Кор',
  'ankle stabilizers': 'Стабилизаторы голеностопа', ankles: 'Голеностоп', brachialis: 'Плечевая мышца',
  deltoids: 'Дельты', feet: 'Стопы', 'grip muscles': 'Мышцы хвата', groin: 'Паховая область', hands: 'Кисти',
  'inner thighs': 'Внутренняя поверхность бедра', 'latissimus dorsi': 'Широчайшие',
  'levator scapulae': 'Мышца, поднимающая лопатку', 'lower abs': 'Низ пресса', quadriceps: 'Квадрицепсы',
  'rear deltoids': 'Задние дельты', rhomboids: 'Ромбовидные', 'rotator cuff': 'Ротаторная манжета',
  'serratus anterior': 'Передняя зубчатая', shins: 'Передняя поверхность голени', soleus: 'Камбаловидная',
  sternocleidomastoid: 'Грудино-ключично-сосцевидная', trapezius: 'Трапеции', 'upper chest': 'Верх груди',
  'wrist extensors': 'Разгибатели кисти', 'wrist flexors': 'Сгибатели кисти', wrists: 'Запястья',
  'bosu ball': 'BOSU', 'elliptical machine': 'Эллипс', hammer: 'Молот', 'olympic barbell': 'Олимпийский гриф',
  roller: 'Ролик', rope: 'Канат', 'skierg machine': 'Лыжный тренажёр', 'sled machine': 'Платформа для жима ногами',
  'stationary bike': 'Велотренажёр', 'stepmill machine': 'Степпер', tire: 'Покрышка', 'trap bar': 'Трэп-гриф',
  'upper body ergometer': 'Ручной эргометр', 'wheel roller': 'Ролик для пресса',
  abs: 'Пресс', abdominals: 'Пресс', biceps: 'Бицепс', triceps: 'Трицепс',
  delts: 'Дельты', shoulders: 'Плечи', pectorals: 'Грудные', chest: 'Грудь',
  lats: 'Широчайшие', 'upper back': 'Верх спины', back: 'Спина', traps: 'Трапеции',
  glutes: 'Ягодицы', quads: 'Квадрицепсы', hamstrings: 'Бицепсы бедра', calves: 'Икры',
  forearms: 'Предплечья', adductors: 'Приводящие', abductors: 'Отводящие',
  spine: 'Разгибатели спины', 'lower back': 'Поясница', 'upper legs': 'Бёдра', 'lower legs': 'Голени',
  'upper arms': 'Плечевой отдел рук', 'lower arms': 'Предплечья', waist: 'Корпус', neck: 'Шея',
  'cardiovascular system': 'Выносливость', barbell: 'Штанга', dumbbell: 'Гантели',
  'body weight': 'Свой вес', cable: 'Блок', 'leverage machine': 'Рычажный тренажёр',
  'smith machine': 'Машина Смита', kettlebell: 'Гиря', band: 'Эспандер',
  'resistance band': 'Резинка', 'stability ball': 'Фитбол', 'medicine ball': 'Медбол',
  'ez barbell': 'EZ-гриф', 'weighted': 'Отягощение', assisted: 'С поддержкой',
}
export function exerciseLabel(value: string) { return labels[value.toLowerCase()] || value }
