// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/goforj/wire"
	"sport/server/internal/app"
	"sport/server/internal/exercises"
)

// Injectors from wire.go:

func initializeApplication(ctx context.Context) (*application, func(), error) {
	config, err := app.LoadConfig(ctx)
	if err != nil {
		return nil, nil, err
	}
	logger, err := newLogger(config)
	if err != nil {
		return nil, nil, err
	}
	pool, cleanup, err := app.NewPostgresPool(ctx, config)
	if err != nil {
		return nil, nil, err
	}
	postgresStore := app.NewPostgresStore(pool)
	catalog, err := newCatalog(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	handler := app.NewHandler(postgresStore, catalog)
	security := app.NewSecurity(postgresStore)
	server, err := newHTTPServer(config, logger, handler, security)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	mainApplication := &application{
		Logger:     logger,
		HTTPServer: server,
	}
	return mainApplication, func() {
		cleanup()
	}, nil
}

// wire.go:

func newCatalog(cfg app.Config) (*exercises.Catalog, error) {
	return exercises.NewCatalog(cfg.Media.BaseURL, cfg.Media.Manifest)
}

var applicationSet = wire.NewSet(app.LoadConfig, newLogger, app.NewPostgresPool, newCatalog, app.NewPostgresStore, wire.Bind(new(app.Store), new(*app.PostgresStore)), app.NewHandler, app.NewSecurity, newHTTPServer, wire.Struct(new(application), "*"))
