// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AdvanceCurrentCycle implements advanceCurrentCycle operation.
//
// Move the current cycle to another week.
//
// POST /v1/cycles/current/advance
func (UnimplementedHandler) AdvanceCurrentCycle(ctx context.Context, req *AdvanceCycleRequest) (r AdvanceCurrentCycleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Bootstrap implements bootstrap operation.
//
// Sets `init=1`. This cookie is not auth.
//
// GET /v1/bootstrap
func (UnimplementedHandler) Bootstrap(ctx context.Context) (r *BootstrapResponseHeaders, _ error) {
	return r, ht.ErrNotImplemented
}

// CalculateProgram implements calculateProgram operation.
//
// Calculate training days from settings and week.
//
// POST /v1/program/calculate
func (UnimplementedHandler) CalculateProgram(ctx context.Context, req *CalculateProgramRequest) (r CalculateProgramRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteCurrentCycleCheckpoint implements deleteCurrentCycleCheckpoint operation.
//
// Delete one progress checkpoint.
//
// DELETE /v1/cycles/current/progress/checkpoints/{checkpointId}
func (UnimplementedHandler) DeleteCurrentCycleCheckpoint(ctx context.Context, params DeleteCurrentCycleCheckpointParams) (r DeleteCurrentCycleCheckpointRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCurrentCycle implements getCurrentCycle operation.
//
// Get current active cycle with editable settings.
//
// GET /v1/cycles/current
func (UnimplementedHandler) GetCurrentCycle(ctx context.Context) (r GetCurrentCycleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetExerciseDetails implements getExerciseDetails operation.
//
// Get details for a program exercise.
//
// GET /v1/exercises/{exerciseKey}
func (UnimplementedHandler) GetExerciseDetails(ctx context.Context, params GetExerciseDetailsParams) (r GetExerciseDetailsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMe implements getMe operation.
//
// Get current authenticated user.
//
// GET /v1/me
func (UnimplementedHandler) GetMe(ctx context.Context) (r GetMeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMyProfile implements getMyProfile operation.
//
// Get athlete profile defaults.
//
// GET /v1/me/profile
func (UnimplementedHandler) GetMyProfile(ctx context.Context) (r GetMyProfileRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProgramOptions implements getProgramOptions operation.
//
// Get selectable program options.
//
// GET /v1/program/options
func (UnimplementedHandler) GetProgramOptions(ctx context.Context) (r *ProgramOptionsResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// Healthz implements healthz operation.
//
// Health check.
//
// GET /healthz
func (UnimplementedHandler) Healthz(ctx context.Context) (r *HealthResponse, _ error) {
	return r, ht.ErrNotImplemented
}

// ListCurrentCycleProgress implements listCurrentCycleProgress operation.
//
// List checkpoints for the current active cycle.
//
// GET /v1/cycles/current/progress
func (UnimplementedHandler) ListCurrentCycleProgress(ctx context.Context, params ListCurrentCycleProgressParams) (r ListCurrentCycleProgressRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Login implements login operation.
//
// Sign in with nickname and password.
//
// POST /v1/auth/login
func (UnimplementedHandler) Login(ctx context.Context, req *LoginRequest) (r LoginRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Logout implements logout operation.
//
// Revoke current session.
//
// POST /v1/auth/logout
func (UnimplementedHandler) Logout(ctx context.Context) (r LogoutRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PutCurrentCycle implements putCurrentCycle operation.
//
// Settings may be changed while progressing through the cycle.
//
// PUT /v1/cycles/current
func (UnimplementedHandler) PutCurrentCycle(ctx context.Context, req *PutCurrentCycleRequest) (r PutCurrentCycleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PutMyProfile implements putMyProfile operation.
//
// Profile changes do not automatically rewrite existing cycle settings.
//
// PUT /v1/me/profile
func (UnimplementedHandler) PutMyProfile(ctx context.Context, req *PutAthleteProfileRequest) (r PutMyProfileRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Register implements register operation.
//
// Create a local user.
//
// POST /v1/auth/register
func (UnimplementedHandler) Register(ctx context.Context, req *RegisterRequest) (r RegisterRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpsertCurrentCycleCheckpoint implements upsertCurrentCycleCheckpoint operation.
//
// Upserts by `(cycle, week, dayId, exerciseKey)` for the MVP.
//
// PUT /v1/cycles/current/progress/checkpoints
func (UnimplementedHandler) UpsertCurrentCycleCheckpoint(ctx context.Context, req *UpsertProgressCheckpointRequest) (r UpsertCurrentCycleCheckpointRes, _ error) {
	return r, ht.ErrNotImplemented
}
