// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/url"
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

// Ref: #/components/schemas/APIError
type APIError struct {
	Code    string   `json:"code"`
	Message string   `json:"message"`
	Details []string `json:"details"`
}

// GetCode returns the value of Code.
func (s *APIError) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *APIError) GetMessage() string {
	return s.Message
}

// GetDetails returns the value of Details.
func (s *APIError) GetDetails() []string {
	return s.Details
}

// SetCode sets the value of Code.
func (s *APIError) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *APIError) SetMessage(val string) {
	s.Message = val
}

// SetDetails sets the value of Details.
func (s *APIError) SetDetails(val []string) {
	s.Details = val
}

type ActivateCycleNotFound ErrorResponse

func (*ActivateCycleNotFound) activateCycleRes() {}

type ActivateCycleUnauthorized ErrorResponse

func (*ActivateCycleUnauthorized) activateCycleRes() {}

type AdvanceCurrentCycleBadRequest ErrorResponse

func (*AdvanceCurrentCycleBadRequest) advanceCurrentCycleRes() {}

type AdvanceCurrentCycleNotFound ErrorResponse

func (*AdvanceCurrentCycleNotFound) advanceCurrentCycleRes() {}

type AdvanceCurrentCycleUnauthorized ErrorResponse

func (*AdvanceCurrentCycleUnauthorized) advanceCurrentCycleRes() {}

// Ref: #/components/schemas/AdvanceCycleRequest
type AdvanceCycleRequest struct {
	TargetWeek ProgramWeek  `json:"targetWeek"`
	Note       OptNilString `json:"note"`
}

// GetTargetWeek returns the value of TargetWeek.
func (s *AdvanceCycleRequest) GetTargetWeek() ProgramWeek {
	return s.TargetWeek
}

// GetNote returns the value of Note.
func (s *AdvanceCycleRequest) GetNote() OptNilString {
	return s.Note
}

// SetTargetWeek sets the value of TargetWeek.
func (s *AdvanceCycleRequest) SetTargetWeek(val ProgramWeek) {
	s.TargetWeek = val
}

// SetNote sets the value of Note.
func (s *AdvanceCycleRequest) SetNote(val OptNilString) {
	s.Note = val
}

// Ref: #/components/schemas/AssistanceOptions
type AssistanceOptions struct {
	Deadlift []SelectOption `json:"deadlift"`
	Bench    []SelectOption `json:"bench"`
	Squat    []SelectOption `json:"squat"`
}

// GetDeadlift returns the value of Deadlift.
func (s *AssistanceOptions) GetDeadlift() []SelectOption {
	return s.Deadlift
}

// GetBench returns the value of Bench.
func (s *AssistanceOptions) GetBench() []SelectOption {
	return s.Bench
}

// GetSquat returns the value of Squat.
func (s *AssistanceOptions) GetSquat() []SelectOption {
	return s.Squat
}

// SetDeadlift sets the value of Deadlift.
func (s *AssistanceOptions) SetDeadlift(val []SelectOption) {
	s.Deadlift = val
}

// SetBench sets the value of Bench.
func (s *AssistanceOptions) SetBench(val []SelectOption) {
	s.Bench = val
}

// SetSquat sets the value of Squat.
func (s *AssistanceOptions) SetSquat(val []SelectOption) {
	s.Squat = val
}

// Ref: #/components/schemas/AssistanceSelection
type AssistanceSelection struct {
	Deadlift string `json:"deadlift"`
	Bench    string `json:"bench"`
	Squat    string `json:"squat"`
}

// GetDeadlift returns the value of Deadlift.
func (s *AssistanceSelection) GetDeadlift() string {
	return s.Deadlift
}

// GetBench returns the value of Bench.
func (s *AssistanceSelection) GetBench() string {
	return s.Bench
}

// GetSquat returns the value of Squat.
func (s *AssistanceSelection) GetSquat() string {
	return s.Squat
}

// SetDeadlift sets the value of Deadlift.
func (s *AssistanceSelection) SetDeadlift(val string) {
	s.Deadlift = val
}

// SetBench sets the value of Bench.
func (s *AssistanceSelection) SetBench(val string) {
	s.Bench = val
}

// SetSquat sets the value of Squat.
func (s *AssistanceSelection) SetSquat(val string) {
	s.Squat = val
}

// Ref: #/components/schemas/AthleteProfile
type AthleteProfile struct {
	OneRepMaxKg              ProfileOneRepMaxes `json:"oneRepMaxKg"`
	PreferredVariant         ProgramVariant     `json:"preferredVariant"`
	PreferredProgressionStep ProgressionStep    `json:"preferredProgressionStep"`
	Notes                    OptNilString       `json:"notes"`
	CreatedAt                time.Time          `json:"createdAt"`
	UpdatedAt                time.Time          `json:"updatedAt"`
}

// GetOneRepMaxKg returns the value of OneRepMaxKg.
func (s *AthleteProfile) GetOneRepMaxKg() ProfileOneRepMaxes {
	return s.OneRepMaxKg
}

// GetPreferredVariant returns the value of PreferredVariant.
func (s *AthleteProfile) GetPreferredVariant() ProgramVariant {
	return s.PreferredVariant
}

// GetPreferredProgressionStep returns the value of PreferredProgressionStep.
func (s *AthleteProfile) GetPreferredProgressionStep() ProgressionStep {
	return s.PreferredProgressionStep
}

// GetNotes returns the value of Notes.
func (s *AthleteProfile) GetNotes() OptNilString {
	return s.Notes
}

// GetCreatedAt returns the value of CreatedAt.
func (s *AthleteProfile) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *AthleteProfile) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetOneRepMaxKg sets the value of OneRepMaxKg.
func (s *AthleteProfile) SetOneRepMaxKg(val ProfileOneRepMaxes) {
	s.OneRepMaxKg = val
}

// SetPreferredVariant sets the value of PreferredVariant.
func (s *AthleteProfile) SetPreferredVariant(val ProgramVariant) {
	s.PreferredVariant = val
}

// SetPreferredProgressionStep sets the value of PreferredProgressionStep.
func (s *AthleteProfile) SetPreferredProgressionStep(val ProgressionStep) {
	s.PreferredProgressionStep = val
}

// SetNotes sets the value of Notes.
func (s *AthleteProfile) SetNotes(val OptNilString) {
	s.Notes = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *AthleteProfile) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *AthleteProfile) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// Ref: #/components/schemas/AthleteProfileInput
type AthleteProfileInput struct {
	OneRepMaxKg              ProfileOneRepMaxes `json:"oneRepMaxKg"`
	PreferredVariant         ProgramVariant     `json:"preferredVariant"`
	PreferredProgressionStep ProgressionStep    `json:"preferredProgressionStep"`
	Notes                    OptNilString       `json:"notes"`
}

// GetOneRepMaxKg returns the value of OneRepMaxKg.
func (s *AthleteProfileInput) GetOneRepMaxKg() ProfileOneRepMaxes {
	return s.OneRepMaxKg
}

// GetPreferredVariant returns the value of PreferredVariant.
func (s *AthleteProfileInput) GetPreferredVariant() ProgramVariant {
	return s.PreferredVariant
}

// GetPreferredProgressionStep returns the value of PreferredProgressionStep.
func (s *AthleteProfileInput) GetPreferredProgressionStep() ProgressionStep {
	return s.PreferredProgressionStep
}

// GetNotes returns the value of Notes.
func (s *AthleteProfileInput) GetNotes() OptNilString {
	return s.Notes
}

// SetOneRepMaxKg sets the value of OneRepMaxKg.
func (s *AthleteProfileInput) SetOneRepMaxKg(val ProfileOneRepMaxes) {
	s.OneRepMaxKg = val
}

// SetPreferredVariant sets the value of PreferredVariant.
func (s *AthleteProfileInput) SetPreferredVariant(val ProgramVariant) {
	s.PreferredVariant = val
}

// SetPreferredProgressionStep sets the value of PreferredProgressionStep.
func (s *AthleteProfileInput) SetPreferredProgressionStep(val ProgressionStep) {
	s.PreferredProgressionStep = val
}

// SetNotes sets the value of Notes.
func (s *AthleteProfileInput) SetNotes(val OptNilString) {
	s.Notes = val
}

// Ref: #/components/schemas/AthleteProfileResponse
type AthleteProfileResponse struct {
	Profile AthleteProfile `json:"profile"`
}

// GetProfile returns the value of Profile.
func (s *AthleteProfileResponse) GetProfile() AthleteProfile {
	return s.Profile
}

// SetProfile sets the value of Profile.
func (s *AthleteProfileResponse) SetProfile(val AthleteProfile) {
	s.Profile = val
}

func (*AthleteProfileResponse) getMyProfileRes() {}
func (*AthleteProfileResponse) putMyProfileRes() {}

// Ref: #/components/schemas/AuthResponse
type AuthResponse struct {
	User User `json:"user"`
}

// GetUser returns the value of User.
func (s *AuthResponse) GetUser() User {
	return s.User
}

// SetUser sets the value of User.
func (s *AuthResponse) SetUser(val User) {
	s.User = val
}

// AuthResponseHeaders wraps AuthResponse with response headers.
type AuthResponseHeaders struct {
	SetCookie OptString
	Response  AuthResponse
}

// GetSetCookie returns the value of SetCookie.
func (s *AuthResponseHeaders) GetSetCookie() OptString {
	return s.SetCookie
}

// GetResponse returns the value of Response.
func (s *AuthResponseHeaders) GetResponse() AuthResponse {
	return s.Response
}

// SetSetCookie sets the value of SetCookie.
func (s *AuthResponseHeaders) SetSetCookie(val OptString) {
	s.SetCookie = val
}

// SetResponse sets the value of Response.
func (s *AuthResponseHeaders) SetResponse(val AuthResponse) {
	s.Response = val
}

func (*AuthResponseHeaders) loginRes()    {}
func (*AuthResponseHeaders) registerRes() {}

// Ref: #/components/schemas/BootstrapResponse
type BootstrapResponse struct {
	InitCookie InitCookieInfo `json:"initCookie"`
	Service    ServiceInfo    `json:"service"`
}

// GetInitCookie returns the value of InitCookie.
func (s *BootstrapResponse) GetInitCookie() InitCookieInfo {
	return s.InitCookie
}

// GetService returns the value of Service.
func (s *BootstrapResponse) GetService() ServiceInfo {
	return s.Service
}

// SetInitCookie sets the value of InitCookie.
func (s *BootstrapResponse) SetInitCookie(val InitCookieInfo) {
	s.InitCookie = val
}

// SetService sets the value of Service.
func (s *BootstrapResponse) SetService(val ServiceInfo) {
	s.Service = val
}

// BootstrapResponseHeaders wraps BootstrapResponse with response headers.
type BootstrapResponseHeaders struct {
	SetCookie OptString
	Response  BootstrapResponse
}

// GetSetCookie returns the value of SetCookie.
func (s *BootstrapResponseHeaders) GetSetCookie() OptString {
	return s.SetCookie
}

// GetResponse returns the value of Response.
func (s *BootstrapResponseHeaders) GetResponse() BootstrapResponse {
	return s.Response
}

// SetSetCookie sets the value of SetCookie.
func (s *BootstrapResponseHeaders) SetSetCookie(val OptString) {
	s.SetCookie = val
}

// SetResponse sets the value of Response.
func (s *BootstrapResponseHeaders) SetResponse(val BootstrapResponse) {
	s.Response = val
}

type CalculateProgramBadRequest ErrorResponse

func (*CalculateProgramBadRequest) calculateProgramRes() {}

// Ref: #/components/schemas/CalculateProgramRequest
type CalculateProgramRequest struct {
	Selection ProgramSelection `json:"selection"`
}

// GetSelection returns the value of Selection.
func (s *CalculateProgramRequest) GetSelection() ProgramSelection {
	return s.Selection
}

// SetSelection sets the value of Selection.
func (s *CalculateProgramRequest) SetSelection(val ProgramSelection) {
	s.Selection = val
}

type CalculateProgramUnauthorized ErrorResponse

func (*CalculateProgramUnauthorized) calculateProgramRes() {}

// Ref: #/components/schemas/CheckpointCompletedData
type CheckpointCompletedData struct {
	Sets     OptNilInt     `json:"sets"`
	RepsText OptNilString  `json:"repsText"`
	WeightKg OptNilFloat64 `json:"weightKg"`
	RpeText  OptNilString  `json:"rpeText"`
}

// GetSets returns the value of Sets.
func (s *CheckpointCompletedData) GetSets() OptNilInt {
	return s.Sets
}

// GetRepsText returns the value of RepsText.
func (s *CheckpointCompletedData) GetRepsText() OptNilString {
	return s.RepsText
}

// GetWeightKg returns the value of WeightKg.
func (s *CheckpointCompletedData) GetWeightKg() OptNilFloat64 {
	return s.WeightKg
}

// GetRpeText returns the value of RpeText.
func (s *CheckpointCompletedData) GetRpeText() OptNilString {
	return s.RpeText
}

// SetSets sets the value of Sets.
func (s *CheckpointCompletedData) SetSets(val OptNilInt) {
	s.Sets = val
}

// SetRepsText sets the value of RepsText.
func (s *CheckpointCompletedData) SetRepsText(val OptNilString) {
	s.RepsText = val
}

// SetWeightKg sets the value of WeightKg.
func (s *CheckpointCompletedData) SetWeightKg(val OptNilFloat64) {
	s.WeightKg = val
}

// SetRpeText sets the value of RpeText.
func (s *CheckpointCompletedData) SetRpeText(val OptNilString) {
	s.RpeText = val
}

// Ref: #/components/schemas/CheckpointPrescriptionSnapshot
type CheckpointPrescriptionSnapshot struct {
	Sets     OptNilInt     `json:"sets"`
	RepsText OptNilString  `json:"repsText"`
	WeightKg OptNilFloat64 `json:"weightKg"`
	RpeText  OptNilString  `json:"rpeText"`
}

// GetSets returns the value of Sets.
func (s *CheckpointPrescriptionSnapshot) GetSets() OptNilInt {
	return s.Sets
}

// GetRepsText returns the value of RepsText.
func (s *CheckpointPrescriptionSnapshot) GetRepsText() OptNilString {
	return s.RepsText
}

// GetWeightKg returns the value of WeightKg.
func (s *CheckpointPrescriptionSnapshot) GetWeightKg() OptNilFloat64 {
	return s.WeightKg
}

// GetRpeText returns the value of RpeText.
func (s *CheckpointPrescriptionSnapshot) GetRpeText() OptNilString {
	return s.RpeText
}

// SetSets sets the value of Sets.
func (s *CheckpointPrescriptionSnapshot) SetSets(val OptNilInt) {
	s.Sets = val
}

// SetRepsText sets the value of RepsText.
func (s *CheckpointPrescriptionSnapshot) SetRepsText(val OptNilString) {
	s.RepsText = val
}

// SetWeightKg sets the value of WeightKg.
func (s *CheckpointPrescriptionSnapshot) SetWeightKg(val OptNilFloat64) {
	s.WeightKg = val
}

// SetRpeText sets the value of RpeText.
func (s *CheckpointPrescriptionSnapshot) SetRpeText(val OptNilString) {
	s.RpeText = val
}

// Ref: #/components/schemas/CheckpointStatus
type CheckpointStatus string

const (
	CheckpointStatusPlanned CheckpointStatus = "planned"
	CheckpointStatusDone    CheckpointStatus = "done"
	CheckpointStatusSkipped CheckpointStatus = "skipped"
	CheckpointStatusPartial CheckpointStatus = "partial"
)

// AllValues returns all CheckpointStatus values.
func (CheckpointStatus) AllValues() []CheckpointStatus {
	return []CheckpointStatus{
		CheckpointStatusPlanned,
		CheckpointStatusDone,
		CheckpointStatusSkipped,
		CheckpointStatusPartial,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CheckpointStatus) MarshalText() ([]byte, error) {
	switch s {
	case CheckpointStatusPlanned:
		return []byte(s), nil
	case CheckpointStatusDone:
		return []byte(s), nil
	case CheckpointStatusSkipped:
		return []byte(s), nil
	case CheckpointStatusPartial:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CheckpointStatus) UnmarshalText(data []byte) error {
	switch CheckpointStatus(data) {
	case CheckpointStatusPlanned:
		*s = CheckpointStatusPlanned
		return nil
	case CheckpointStatusDone:
		*s = CheckpointStatusDone
		return nil
	case CheckpointStatusSkipped:
		*s = CheckpointStatusSkipped
		return nil
	case CheckpointStatusPartial:
		*s = CheckpointStatusPartial
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type CreateCycleBadRequest ErrorResponse

func (*CreateCycleBadRequest) createCycleRes() {}

type CreateCycleUnauthorized ErrorResponse

func (*CreateCycleUnauthorized) createCycleRes() {}

// Ref: #/components/schemas/CycleResponse
type CycleResponse struct {
	Cycle ProgramCycle `json:"cycle"`
}

// GetCycle returns the value of Cycle.
func (s *CycleResponse) GetCycle() ProgramCycle {
	return s.Cycle
}

// SetCycle sets the value of Cycle.
func (s *CycleResponse) SetCycle(val ProgramCycle) {
	s.Cycle = val
}

func (*CycleResponse) activateCycleRes()       {}
func (*CycleResponse) advanceCurrentCycleRes() {}
func (*CycleResponse) createCycleRes()         {}
func (*CycleResponse) getCurrentCycleRes()     {}
func (*CycleResponse) putCurrentCycleRes()     {}
func (*CycleResponse) putCycleRes()            {}

// Ref: #/components/schemas/CycleSettings
type CycleSettings struct {
	OneRepMaxKg     OneRepMaxes         `json:"oneRepMaxKg"`
	Variant         ProgramVariant      `json:"variant"`
	ProgressionStep ProgressionStep     `json:"progressionStep"`
	Assistance      AssistanceSelection `json:"assistance"`
	Gpp             GPPSelection        `json:"gpp"`
}

// GetOneRepMaxKg returns the value of OneRepMaxKg.
func (s *CycleSettings) GetOneRepMaxKg() OneRepMaxes {
	return s.OneRepMaxKg
}

// GetVariant returns the value of Variant.
func (s *CycleSettings) GetVariant() ProgramVariant {
	return s.Variant
}

// GetProgressionStep returns the value of ProgressionStep.
func (s *CycleSettings) GetProgressionStep() ProgressionStep {
	return s.ProgressionStep
}

// GetAssistance returns the value of Assistance.
func (s *CycleSettings) GetAssistance() AssistanceSelection {
	return s.Assistance
}

// GetGpp returns the value of Gpp.
func (s *CycleSettings) GetGpp() GPPSelection {
	return s.Gpp
}

// SetOneRepMaxKg sets the value of OneRepMaxKg.
func (s *CycleSettings) SetOneRepMaxKg(val OneRepMaxes) {
	s.OneRepMaxKg = val
}

// SetVariant sets the value of Variant.
func (s *CycleSettings) SetVariant(val ProgramVariant) {
	s.Variant = val
}

// SetProgressionStep sets the value of ProgressionStep.
func (s *CycleSettings) SetProgressionStep(val ProgressionStep) {
	s.ProgressionStep = val
}

// SetAssistance sets the value of Assistance.
func (s *CycleSettings) SetAssistance(val AssistanceSelection) {
	s.Assistance = val
}

// SetGpp sets the value of Gpp.
func (s *CycleSettings) SetGpp(val GPPSelection) {
	s.Gpp = val
}

// Ref: #/components/schemas/CycleStatus
type CycleStatus string

const (
	CycleStatusActive    CycleStatus = "active"
	CycleStatusCompleted CycleStatus = "completed"
	CycleStatusArchived  CycleStatus = "archived"
)

// AllValues returns all CycleStatus values.
func (CycleStatus) AllValues() []CycleStatus {
	return []CycleStatus{
		CycleStatusActive,
		CycleStatusCompleted,
		CycleStatusArchived,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CycleStatus) MarshalText() ([]byte, error) {
	switch s {
	case CycleStatusActive:
		return []byte(s), nil
	case CycleStatusCompleted:
		return []byte(s), nil
	case CycleStatusArchived:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CycleStatus) UnmarshalText(data []byte) error {
	switch CycleStatus(data) {
	case CycleStatusActive:
		*s = CycleStatusActive
		return nil
	case CycleStatusCompleted:
		*s = CycleStatusCompleted
		return nil
	case CycleStatusArchived:
		*s = CycleStatusArchived
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/CyclesResponse
type CyclesResponse struct {
	Cycles         []ProgramCycle `json:"cycles"`
	CurrentCycleId OptNilUUID     `json:"currentCycleId"`
}

// GetCycles returns the value of Cycles.
func (s *CyclesResponse) GetCycles() []ProgramCycle {
	return s.Cycles
}

// GetCurrentCycleId returns the value of CurrentCycleId.
func (s *CyclesResponse) GetCurrentCycleId() OptNilUUID {
	return s.CurrentCycleId
}

// SetCycles sets the value of Cycles.
func (s *CyclesResponse) SetCycles(val []ProgramCycle) {
	s.Cycles = val
}

// SetCurrentCycleId sets the value of CurrentCycleId.
func (s *CyclesResponse) SetCurrentCycleId(val OptNilUUID) {
	s.CurrentCycleId = val
}

func (*CyclesResponse) listCyclesRes() {}

// DeleteCurrentCycleCheckpointNoContent is response for DeleteCurrentCycleCheckpoint operation.
type DeleteCurrentCycleCheckpointNoContent struct{}

func (*DeleteCurrentCycleCheckpointNoContent) deleteCurrentCycleCheckpointRes() {}

type DeleteCurrentCycleCheckpointNotFound ErrorResponse

func (*DeleteCurrentCycleCheckpointNotFound) deleteCurrentCycleCheckpointRes() {}

type DeleteCurrentCycleCheckpointUnauthorized ErrorResponse

func (*DeleteCurrentCycleCheckpointUnauthorized) deleteCurrentCycleCheckpointRes() {}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Error APIError `json:"error"`
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() APIError {
	return s.Error
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val APIError) {
	s.Error = val
}

func (*ErrorResponse) getMeRes()             {}
func (*ErrorResponse) getMyProfileRes()      {}
func (*ErrorResponse) getProgramOptionsRes() {}
func (*ErrorResponse) listCyclesRes()        {}
func (*ErrorResponse) listExercisesRes()     {}
func (*ErrorResponse) logoutRes()            {}

// Ref: #/components/schemas/ExerciseCatalogItem
type ExerciseCatalogItem struct {
	DatasetExerciseId string        `json:"datasetExerciseId"`
	Name              string        `json:"name"`
	NameRu            OptNilString  `json:"nameRu"`
	Category          OptNilString  `json:"category"`
	BodyPart          OptNilString  `json:"bodyPart"`
	Equipment         OptNilString  `json:"equipment"`
	TargetMuscles     []string      `json:"targetMuscles"`
	SecondaryMuscles  []string      `json:"secondaryMuscles"`
	Instructions      []string      `json:"instructions"`
	Media             ExerciseMedia `json:"media"`
}

// GetDatasetExerciseId returns the value of DatasetExerciseId.
func (s *ExerciseCatalogItem) GetDatasetExerciseId() string {
	return s.DatasetExerciseId
}

// GetName returns the value of Name.
func (s *ExerciseCatalogItem) GetName() string {
	return s.Name
}

// GetNameRu returns the value of NameRu.
func (s *ExerciseCatalogItem) GetNameRu() OptNilString {
	return s.NameRu
}

// GetCategory returns the value of Category.
func (s *ExerciseCatalogItem) GetCategory() OptNilString {
	return s.Category
}

// GetBodyPart returns the value of BodyPart.
func (s *ExerciseCatalogItem) GetBodyPart() OptNilString {
	return s.BodyPart
}

// GetEquipment returns the value of Equipment.
func (s *ExerciseCatalogItem) GetEquipment() OptNilString {
	return s.Equipment
}

// GetTargetMuscles returns the value of TargetMuscles.
func (s *ExerciseCatalogItem) GetTargetMuscles() []string {
	return s.TargetMuscles
}

// GetSecondaryMuscles returns the value of SecondaryMuscles.
func (s *ExerciseCatalogItem) GetSecondaryMuscles() []string {
	return s.SecondaryMuscles
}

// GetInstructions returns the value of Instructions.
func (s *ExerciseCatalogItem) GetInstructions() []string {
	return s.Instructions
}

// GetMedia returns the value of Media.
func (s *ExerciseCatalogItem) GetMedia() ExerciseMedia {
	return s.Media
}

// SetDatasetExerciseId sets the value of DatasetExerciseId.
func (s *ExerciseCatalogItem) SetDatasetExerciseId(val string) {
	s.DatasetExerciseId = val
}

// SetName sets the value of Name.
func (s *ExerciseCatalogItem) SetName(val string) {
	s.Name = val
}

// SetNameRu sets the value of NameRu.
func (s *ExerciseCatalogItem) SetNameRu(val OptNilString) {
	s.NameRu = val
}

// SetCategory sets the value of Category.
func (s *ExerciseCatalogItem) SetCategory(val OptNilString) {
	s.Category = val
}

// SetBodyPart sets the value of BodyPart.
func (s *ExerciseCatalogItem) SetBodyPart(val OptNilString) {
	s.BodyPart = val
}

// SetEquipment sets the value of Equipment.
func (s *ExerciseCatalogItem) SetEquipment(val OptNilString) {
	s.Equipment = val
}

// SetTargetMuscles sets the value of TargetMuscles.
func (s *ExerciseCatalogItem) SetTargetMuscles(val []string) {
	s.TargetMuscles = val
}

// SetSecondaryMuscles sets the value of SecondaryMuscles.
func (s *ExerciseCatalogItem) SetSecondaryMuscles(val []string) {
	s.SecondaryMuscles = val
}

// SetInstructions sets the value of Instructions.
func (s *ExerciseCatalogItem) SetInstructions(val []string) {
	s.Instructions = val
}

// SetMedia sets the value of Media.
func (s *ExerciseCatalogItem) SetMedia(val ExerciseMedia) {
	s.Media = val
}

// Ref: #/components/schemas/ExerciseCatalogItemResponse
type ExerciseCatalogItemResponse struct {
	Exercise ExerciseCatalogItem `json:"exercise"`
}

// GetExercise returns the value of Exercise.
func (s *ExerciseCatalogItemResponse) GetExercise() ExerciseCatalogItem {
	return s.Exercise
}

// SetExercise sets the value of Exercise.
func (s *ExerciseCatalogItemResponse) SetExercise(val ExerciseCatalogItem) {
	s.Exercise = val
}

func (*ExerciseCatalogItemResponse) getCatalogExerciseRes() {}

// Ref: #/components/schemas/ExerciseCatalogListResponse
type ExerciseCatalogListResponse struct {
	Items  []ExerciseCatalogItem `json:"items"`
	Total  int                   `json:"total"`
	Limit  int                   `json:"limit"`
	Offset int                   `json:"offset"`
}

// GetItems returns the value of Items.
func (s *ExerciseCatalogListResponse) GetItems() []ExerciseCatalogItem {
	return s.Items
}

// GetTotal returns the value of Total.
func (s *ExerciseCatalogListResponse) GetTotal() int {
	return s.Total
}

// GetLimit returns the value of Limit.
func (s *ExerciseCatalogListResponse) GetLimit() int {
	return s.Limit
}

// GetOffset returns the value of Offset.
func (s *ExerciseCatalogListResponse) GetOffset() int {
	return s.Offset
}

// SetItems sets the value of Items.
func (s *ExerciseCatalogListResponse) SetItems(val []ExerciseCatalogItem) {
	s.Items = val
}

// SetTotal sets the value of Total.
func (s *ExerciseCatalogListResponse) SetTotal(val int) {
	s.Total = val
}

// SetLimit sets the value of Limit.
func (s *ExerciseCatalogListResponse) SetLimit(val int) {
	s.Limit = val
}

// SetOffset sets the value of Offset.
func (s *ExerciseCatalogListResponse) SetOffset(val int) {
	s.Offset = val
}

func (*ExerciseCatalogListResponse) listExercisesRes() {}

// Ref: #/components/schemas/ExerciseDetails
type ExerciseDetails struct {
	ExerciseKey       string                     `json:"exerciseKey"`
	Name              string                     `json:"name"`
	DatasetExerciseId OptNilString               `json:"datasetExerciseId"`
	DatasetName       OptNilString               `json:"datasetName"`
	AliasStatus       ExerciseDetailsAliasStatus `json:"aliasStatus"`
	Equipment         OptNilString               `json:"equipment"`
	TargetMuscles     []string                   `json:"targetMuscles"`
	SecondaryMuscles  []string                   `json:"secondaryMuscles"`
	Instructions      []string                   `json:"instructions"`
	Media             ExerciseMedia              `json:"media"`
}

// GetExerciseKey returns the value of ExerciseKey.
func (s *ExerciseDetails) GetExerciseKey() string {
	return s.ExerciseKey
}

// GetName returns the value of Name.
func (s *ExerciseDetails) GetName() string {
	return s.Name
}

// GetDatasetExerciseId returns the value of DatasetExerciseId.
func (s *ExerciseDetails) GetDatasetExerciseId() OptNilString {
	return s.DatasetExerciseId
}

// GetDatasetName returns the value of DatasetName.
func (s *ExerciseDetails) GetDatasetName() OptNilString {
	return s.DatasetName
}

// GetAliasStatus returns the value of AliasStatus.
func (s *ExerciseDetails) GetAliasStatus() ExerciseDetailsAliasStatus {
	return s.AliasStatus
}

// GetEquipment returns the value of Equipment.
func (s *ExerciseDetails) GetEquipment() OptNilString {
	return s.Equipment
}

// GetTargetMuscles returns the value of TargetMuscles.
func (s *ExerciseDetails) GetTargetMuscles() []string {
	return s.TargetMuscles
}

// GetSecondaryMuscles returns the value of SecondaryMuscles.
func (s *ExerciseDetails) GetSecondaryMuscles() []string {
	return s.SecondaryMuscles
}

// GetInstructions returns the value of Instructions.
func (s *ExerciseDetails) GetInstructions() []string {
	return s.Instructions
}

// GetMedia returns the value of Media.
func (s *ExerciseDetails) GetMedia() ExerciseMedia {
	return s.Media
}

// SetExerciseKey sets the value of ExerciseKey.
func (s *ExerciseDetails) SetExerciseKey(val string) {
	s.ExerciseKey = val
}

// SetName sets the value of Name.
func (s *ExerciseDetails) SetName(val string) {
	s.Name = val
}

// SetDatasetExerciseId sets the value of DatasetExerciseId.
func (s *ExerciseDetails) SetDatasetExerciseId(val OptNilString) {
	s.DatasetExerciseId = val
}

// SetDatasetName sets the value of DatasetName.
func (s *ExerciseDetails) SetDatasetName(val OptNilString) {
	s.DatasetName = val
}

// SetAliasStatus sets the value of AliasStatus.
func (s *ExerciseDetails) SetAliasStatus(val ExerciseDetailsAliasStatus) {
	s.AliasStatus = val
}

// SetEquipment sets the value of Equipment.
func (s *ExerciseDetails) SetEquipment(val OptNilString) {
	s.Equipment = val
}

// SetTargetMuscles sets the value of TargetMuscles.
func (s *ExerciseDetails) SetTargetMuscles(val []string) {
	s.TargetMuscles = val
}

// SetSecondaryMuscles sets the value of SecondaryMuscles.
func (s *ExerciseDetails) SetSecondaryMuscles(val []string) {
	s.SecondaryMuscles = val
}

// SetInstructions sets the value of Instructions.
func (s *ExerciseDetails) SetInstructions(val []string) {
	s.Instructions = val
}

// SetMedia sets the value of Media.
func (s *ExerciseDetails) SetMedia(val ExerciseMedia) {
	s.Media = val
}

type ExerciseDetailsAliasStatus string

const (
	ExerciseDetailsAliasStatusConfirmed   ExerciseDetailsAliasStatus = "confirmed"
	ExerciseDetailsAliasStatusMissing     ExerciseDetailsAliasStatus = "missing"
	ExerciseDetailsAliasStatusNeedsReview ExerciseDetailsAliasStatus = "needs_review"
)

// AllValues returns all ExerciseDetailsAliasStatus values.
func (ExerciseDetailsAliasStatus) AllValues() []ExerciseDetailsAliasStatus {
	return []ExerciseDetailsAliasStatus{
		ExerciseDetailsAliasStatusConfirmed,
		ExerciseDetailsAliasStatusMissing,
		ExerciseDetailsAliasStatusNeedsReview,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ExerciseDetailsAliasStatus) MarshalText() ([]byte, error) {
	switch s {
	case ExerciseDetailsAliasStatusConfirmed:
		return []byte(s), nil
	case ExerciseDetailsAliasStatusMissing:
		return []byte(s), nil
	case ExerciseDetailsAliasStatusNeedsReview:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ExerciseDetailsAliasStatus) UnmarshalText(data []byte) error {
	switch ExerciseDetailsAliasStatus(data) {
	case ExerciseDetailsAliasStatusConfirmed:
		*s = ExerciseDetailsAliasStatusConfirmed
		return nil
	case ExerciseDetailsAliasStatusMissing:
		*s = ExerciseDetailsAliasStatusMissing
		return nil
	case ExerciseDetailsAliasStatusNeedsReview:
		*s = ExerciseDetailsAliasStatusNeedsReview
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ExerciseDetailsResponse
type ExerciseDetailsResponse struct {
	Exercise ExerciseDetails `json:"exercise"`
}

// GetExercise returns the value of Exercise.
func (s *ExerciseDetailsResponse) GetExercise() ExerciseDetails {
	return s.Exercise
}

// SetExercise sets the value of Exercise.
func (s *ExerciseDetailsResponse) SetExercise(val ExerciseDetails) {
	s.Exercise = val
}

func (*ExerciseDetailsResponse) getExerciseDetailsRes() {}

// Ref: #/components/schemas/ExerciseMedia
type ExerciseMedia struct {
	Status     ExerciseMediaStatus `json:"status"`
	GifUrl     OptNilURI           `json:"gifUrl"`
	StorageKey OptNilString        `json:"storageKey"`
	Provenance OptNilString        `json:"provenance"`
	Width      OptNilInt           `json:"width"`
	Height     OptNilInt           `json:"height"`
	UpdatedAt  OptNilDateTime      `json:"updatedAt"`
}

// GetStatus returns the value of Status.
func (s *ExerciseMedia) GetStatus() ExerciseMediaStatus {
	return s.Status
}

// GetGifUrl returns the value of GifUrl.
func (s *ExerciseMedia) GetGifUrl() OptNilURI {
	return s.GifUrl
}

// GetStorageKey returns the value of StorageKey.
func (s *ExerciseMedia) GetStorageKey() OptNilString {
	return s.StorageKey
}

// GetProvenance returns the value of Provenance.
func (s *ExerciseMedia) GetProvenance() OptNilString {
	return s.Provenance
}

// GetWidth returns the value of Width.
func (s *ExerciseMedia) GetWidth() OptNilInt {
	return s.Width
}

// GetHeight returns the value of Height.
func (s *ExerciseMedia) GetHeight() OptNilInt {
	return s.Height
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *ExerciseMedia) GetUpdatedAt() OptNilDateTime {
	return s.UpdatedAt
}

// SetStatus sets the value of Status.
func (s *ExerciseMedia) SetStatus(val ExerciseMediaStatus) {
	s.Status = val
}

// SetGifUrl sets the value of GifUrl.
func (s *ExerciseMedia) SetGifUrl(val OptNilURI) {
	s.GifUrl = val
}

// SetStorageKey sets the value of StorageKey.
func (s *ExerciseMedia) SetStorageKey(val OptNilString) {
	s.StorageKey = val
}

// SetProvenance sets the value of Provenance.
func (s *ExerciseMedia) SetProvenance(val OptNilString) {
	s.Provenance = val
}

// SetWidth sets the value of Width.
func (s *ExerciseMedia) SetWidth(val OptNilInt) {
	s.Width = val
}

// SetHeight sets the value of Height.
func (s *ExerciseMedia) SetHeight(val OptNilInt) {
	s.Height = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *ExerciseMedia) SetUpdatedAt(val OptNilDateTime) {
	s.UpdatedAt = val
}

type ExerciseMediaStatus string

const (
	ExerciseMediaStatusAvailable ExerciseMediaStatus = "available"
	ExerciseMediaStatusMissing   ExerciseMediaStatus = "missing"
)

// AllValues returns all ExerciseMediaStatus values.
func (ExerciseMediaStatus) AllValues() []ExerciseMediaStatus {
	return []ExerciseMediaStatus{
		ExerciseMediaStatusAvailable,
		ExerciseMediaStatusMissing,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ExerciseMediaStatus) MarshalText() ([]byte, error) {
	switch s {
	case ExerciseMediaStatusAvailable:
		return []byte(s), nil
	case ExerciseMediaStatusMissing:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ExerciseMediaStatus) UnmarshalText(data []byte) error {
	switch ExerciseMediaStatus(data) {
	case ExerciseMediaStatusAvailable:
		*s = ExerciseMediaStatusAvailable
		return nil
	case ExerciseMediaStatusMissing:
		*s = ExerciseMediaStatusMissing
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/GPPOptions
type GPPOptions struct {
	Abs            []SelectOption `json:"abs"`
	Triceps        []SelectOption `json:"triceps"`
	HorizontalPull []SelectOption `json:"horizontalPull"`
	Biceps         []SelectOption `json:"biceps"`
	VerticalPull   []SelectOption `json:"verticalPull"`
	OverheadPress  []SelectOption `json:"overheadPress"`
}

// GetAbs returns the value of Abs.
func (s *GPPOptions) GetAbs() []SelectOption {
	return s.Abs
}

// GetTriceps returns the value of Triceps.
func (s *GPPOptions) GetTriceps() []SelectOption {
	return s.Triceps
}

// GetHorizontalPull returns the value of HorizontalPull.
func (s *GPPOptions) GetHorizontalPull() []SelectOption {
	return s.HorizontalPull
}

// GetBiceps returns the value of Biceps.
func (s *GPPOptions) GetBiceps() []SelectOption {
	return s.Biceps
}

// GetVerticalPull returns the value of VerticalPull.
func (s *GPPOptions) GetVerticalPull() []SelectOption {
	return s.VerticalPull
}

// GetOverheadPress returns the value of OverheadPress.
func (s *GPPOptions) GetOverheadPress() []SelectOption {
	return s.OverheadPress
}

// SetAbs sets the value of Abs.
func (s *GPPOptions) SetAbs(val []SelectOption) {
	s.Abs = val
}

// SetTriceps sets the value of Triceps.
func (s *GPPOptions) SetTriceps(val []SelectOption) {
	s.Triceps = val
}

// SetHorizontalPull sets the value of HorizontalPull.
func (s *GPPOptions) SetHorizontalPull(val []SelectOption) {
	s.HorizontalPull = val
}

// SetBiceps sets the value of Biceps.
func (s *GPPOptions) SetBiceps(val []SelectOption) {
	s.Biceps = val
}

// SetVerticalPull sets the value of VerticalPull.
func (s *GPPOptions) SetVerticalPull(val []SelectOption) {
	s.VerticalPull = val
}

// SetOverheadPress sets the value of OverheadPress.
func (s *GPPOptions) SetOverheadPress(val []SelectOption) {
	s.OverheadPress = val
}

// Ref: #/components/schemas/GPPSelection
type GPPSelection struct {
	Abs            NilString `json:"abs"`
	Triceps        NilString `json:"triceps"`
	HorizontalPull NilString `json:"horizontalPull"`
	Biceps         NilString `json:"biceps"`
	VerticalPull   NilString `json:"verticalPull"`
	OverheadPress  NilString `json:"overheadPress"`
}

// GetAbs returns the value of Abs.
func (s *GPPSelection) GetAbs() NilString {
	return s.Abs
}

// GetTriceps returns the value of Triceps.
func (s *GPPSelection) GetTriceps() NilString {
	return s.Triceps
}

// GetHorizontalPull returns the value of HorizontalPull.
func (s *GPPSelection) GetHorizontalPull() NilString {
	return s.HorizontalPull
}

// GetBiceps returns the value of Biceps.
func (s *GPPSelection) GetBiceps() NilString {
	return s.Biceps
}

// GetVerticalPull returns the value of VerticalPull.
func (s *GPPSelection) GetVerticalPull() NilString {
	return s.VerticalPull
}

// GetOverheadPress returns the value of OverheadPress.
func (s *GPPSelection) GetOverheadPress() NilString {
	return s.OverheadPress
}

// SetAbs sets the value of Abs.
func (s *GPPSelection) SetAbs(val NilString) {
	s.Abs = val
}

// SetTriceps sets the value of Triceps.
func (s *GPPSelection) SetTriceps(val NilString) {
	s.Triceps = val
}

// SetHorizontalPull sets the value of HorizontalPull.
func (s *GPPSelection) SetHorizontalPull(val NilString) {
	s.HorizontalPull = val
}

// SetBiceps sets the value of Biceps.
func (s *GPPSelection) SetBiceps(val NilString) {
	s.Biceps = val
}

// SetVerticalPull sets the value of VerticalPull.
func (s *GPPSelection) SetVerticalPull(val NilString) {
	s.VerticalPull = val
}

// SetOverheadPress sets the value of OverheadPress.
func (s *GPPSelection) SetOverheadPress(val NilString) {
	s.OverheadPress = val
}

type GetCatalogExerciseNotFound ErrorResponse

func (*GetCatalogExerciseNotFound) getCatalogExerciseRes() {}

type GetCatalogExerciseUnauthorized ErrorResponse

func (*GetCatalogExerciseUnauthorized) getCatalogExerciseRes() {}

type GetCurrentCycleNotFound ErrorResponse

func (*GetCurrentCycleNotFound) getCurrentCycleRes() {}

type GetCurrentCyclePlanNotFound ErrorResponse

func (*GetCurrentCyclePlanNotFound) getCurrentCyclePlanRes() {}

type GetCurrentCyclePlanUnauthorized ErrorResponse

func (*GetCurrentCyclePlanUnauthorized) getCurrentCyclePlanRes() {}

type GetCurrentCycleUnauthorized ErrorResponse

func (*GetCurrentCycleUnauthorized) getCurrentCycleRes() {}

type GetExerciseDetailsNotFound ErrorResponse

func (*GetExerciseDetailsNotFound) getExerciseDetailsRes() {}

type GetExerciseDetailsUnauthorized ErrorResponse

func (*GetExerciseDetailsUnauthorized) getExerciseDetailsRes() {}

// Ref: #/components/schemas/HealthResponse
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
}

// GetStatus returns the value of Status.
func (s *HealthResponse) GetStatus() HealthResponseStatus {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *HealthResponse) SetStatus(val HealthResponseStatus) {
	s.Status = val
}

type HealthResponseStatus string

const (
	HealthResponseStatusOk HealthResponseStatus = "ok"
)

// AllValues returns all HealthResponseStatus values.
func (HealthResponseStatus) AllValues() []HealthResponseStatus {
	return []HealthResponseStatus{
		HealthResponseStatusOk,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s HealthResponseStatus) MarshalText() ([]byte, error) {
	switch s {
	case HealthResponseStatusOk:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *HealthResponseStatus) UnmarshalText(data []byte) error {
	switch HealthResponseStatus(data) {
	case HealthResponseStatusOk:
		*s = HealthResponseStatusOk
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/InitCookieInfo
type InitCookieInfo struct {
	Name       string `json:"name"`
	Value      string `json:"value"`
	JsReadable bool   `json:"jsReadable"`
	Purpose    string `json:"purpose"`
}

// GetName returns the value of Name.
func (s *InitCookieInfo) GetName() string {
	return s.Name
}

// GetValue returns the value of Value.
func (s *InitCookieInfo) GetValue() string {
	return s.Value
}

// GetJsReadable returns the value of JsReadable.
func (s *InitCookieInfo) GetJsReadable() bool {
	return s.JsReadable
}

// GetPurpose returns the value of Purpose.
func (s *InitCookieInfo) GetPurpose() string {
	return s.Purpose
}

// SetName sets the value of Name.
func (s *InitCookieInfo) SetName(val string) {
	s.Name = val
}

// SetValue sets the value of Value.
func (s *InitCookieInfo) SetValue(val string) {
	s.Value = val
}

// SetJsReadable sets the value of JsReadable.
func (s *InitCookieInfo) SetJsReadable(val bool) {
	s.JsReadable = val
}

// SetPurpose sets the value of Purpose.
func (s *InitCookieInfo) SetPurpose(val string) {
	s.Purpose = val
}

type ListCurrentCycleProgressNotFound ErrorResponse

func (*ListCurrentCycleProgressNotFound) listCurrentCycleProgressRes() {}

type ListCurrentCycleProgressUnauthorized ErrorResponse

func (*ListCurrentCycleProgressUnauthorized) listCurrentCycleProgressRes() {}

type LoginBadRequest ErrorResponse

func (*LoginBadRequest) loginRes() {}

// Ref: #/components/schemas/LoginRequest
type LoginRequest struct {
	Nickname Nickname `json:"nickname"`
	Password Password `json:"password"`
}

// GetNickname returns the value of Nickname.
func (s *LoginRequest) GetNickname() Nickname {
	return s.Nickname
}

// GetPassword returns the value of Password.
func (s *LoginRequest) GetPassword() Password {
	return s.Password
}

// SetNickname sets the value of Nickname.
func (s *LoginRequest) SetNickname(val Nickname) {
	s.Nickname = val
}

// SetPassword sets the value of Password.
func (s *LoginRequest) SetPassword(val Password) {
	s.Password = val
}

type LoginUnauthorized ErrorResponse

func (*LoginUnauthorized) loginRes() {}

// LogoutNoContent is response for Logout operation.
type LogoutNoContent struct {
	SetCookie OptString
}

// GetSetCookie returns the value of SetCookie.
func (s *LogoutNoContent) GetSetCookie() OptString {
	return s.SetCookie
}

// SetSetCookie sets the value of SetCookie.
func (s *LogoutNoContent) SetSetCookie(val OptString) {
	s.SetCookie = val
}

func (*LogoutNoContent) logoutRes() {}

// Ref: #/components/schemas/MeResponse
type MeResponse struct {
	User User `json:"user"`
}

// GetUser returns the value of User.
func (s *MeResponse) GetUser() User {
	return s.User
}

// SetUser sets the value of User.
func (s *MeResponse) SetUser(val User) {
	s.User = val
}

func (*MeResponse) getMeRes() {}

type Nickname string

// NewNilFloat64 returns new NilFloat64 with value set to v.
func NewNilFloat64(v float64) NilFloat64 {
	return NilFloat64{
		Value: v,
	}
}

// NilFloat64 is nullable float64.
type NilFloat64 struct {
	Value float64
	Null  bool
}

// SetTo sets value to v.
func (o *NilFloat64) SetTo(v float64) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilFloat64) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilFloat64) SetToNull() {
	o.Null = true
	var v float64
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilFloat64) Get() (v float64, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewNilString returns new NilString with value set to v.
func NewNilString(v string) NilString {
	return NilString{
		Value: v,
	}
}

// NilString is nullable string.
type NilString struct {
	Value string
	Null  bool
}

// SetTo sets value to v.
func (o *NilString) SetTo(v string) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilString) SetToNull() {
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/OneRepMaxes
type OneRepMaxes struct {
	Deadlift float64 `json:"deadlift"`
	Bench    float64 `json:"bench"`
	Squat    float64 `json:"squat"`
}

// GetDeadlift returns the value of Deadlift.
func (s *OneRepMaxes) GetDeadlift() float64 {
	return s.Deadlift
}

// GetBench returns the value of Bench.
func (s *OneRepMaxes) GetBench() float64 {
	return s.Bench
}

// GetSquat returns the value of Squat.
func (s *OneRepMaxes) GetSquat() float64 {
	return s.Squat
}

// SetDeadlift sets the value of Deadlift.
func (s *OneRepMaxes) SetDeadlift(val float64) {
	s.Deadlift = val
}

// SetBench sets the value of Bench.
func (s *OneRepMaxes) SetBench(val float64) {
	s.Bench = val
}

// SetSquat sets the value of Squat.
func (s *OneRepMaxes) SetSquat(val float64) {
	s.Squat = val
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCheckpointCompletedData returns new OptCheckpointCompletedData with value set to v.
func NewOptCheckpointCompletedData(v CheckpointCompletedData) OptCheckpointCompletedData {
	return OptCheckpointCompletedData{
		Value: v,
		Set:   true,
	}
}

// OptCheckpointCompletedData is optional CheckpointCompletedData.
type OptCheckpointCompletedData struct {
	Value CheckpointCompletedData
	Set   bool
}

// IsSet returns true if OptCheckpointCompletedData was set.
func (o OptCheckpointCompletedData) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCheckpointCompletedData) Reset() {
	var v CheckpointCompletedData
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCheckpointCompletedData) SetTo(v CheckpointCompletedData) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCheckpointCompletedData) Get() (v CheckpointCompletedData, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCheckpointCompletedData) Or(d CheckpointCompletedData) CheckpointCompletedData {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCheckpointPrescriptionSnapshot returns new OptCheckpointPrescriptionSnapshot with value set to v.
func NewOptCheckpointPrescriptionSnapshot(v CheckpointPrescriptionSnapshot) OptCheckpointPrescriptionSnapshot {
	return OptCheckpointPrescriptionSnapshot{
		Value: v,
		Set:   true,
	}
}

// OptCheckpointPrescriptionSnapshot is optional CheckpointPrescriptionSnapshot.
type OptCheckpointPrescriptionSnapshot struct {
	Value CheckpointPrescriptionSnapshot
	Set   bool
}

// IsSet returns true if OptCheckpointPrescriptionSnapshot was set.
func (o OptCheckpointPrescriptionSnapshot) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCheckpointPrescriptionSnapshot) Reset() {
	var v CheckpointPrescriptionSnapshot
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCheckpointPrescriptionSnapshot) SetTo(v CheckpointPrescriptionSnapshot) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCheckpointPrescriptionSnapshot) Get() (v CheckpointPrescriptionSnapshot, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCheckpointPrescriptionSnapshot) Or(d CheckpointPrescriptionSnapshot) CheckpointPrescriptionSnapshot {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilDateTime returns new OptNilDateTime with value set to v.
func NewOptNilDateTime(v time.Time) OptNilDateTime {
	return OptNilDateTime{
		Value: v,
		Set:   true,
	}
}

// OptNilDateTime is optional nullable time.Time.
type OptNilDateTime struct {
	Value time.Time
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilDateTime was set.
func (o OptNilDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilDateTime) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilDateTime) SetToNull() {
	o.Set = true
	o.Null = true
	var v time.Time
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilDateTime) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilDateTime) Get() (v time.Time, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilFloat64 returns new OptNilFloat64 with value set to v.
func NewOptNilFloat64(v float64) OptNilFloat64 {
	return OptNilFloat64{
		Value: v,
		Set:   true,
	}
}

// OptNilFloat64 is optional nullable float64.
type OptNilFloat64 struct {
	Value float64
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilFloat64 was set.
func (o OptNilFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilFloat64) SetTo(v float64) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilFloat64) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilFloat64) SetToNull() {
	o.Set = true
	o.Null = true
	var v float64
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilFloat64) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilFloat64) Get() (v float64, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilInt returns new OptNilInt with value set to v.
func NewOptNilInt(v int) OptNilInt {
	return OptNilInt{
		Value: v,
		Set:   true,
	}
}

// OptNilInt is optional nullable int.
type OptNilInt struct {
	Value int
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilInt was set.
func (o OptNilInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilInt) SetTo(v int) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilInt) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilInt) SetToNull() {
	o.Set = true
	o.Null = true
	var v int
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilInt) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilInt) Get() (v int, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilString) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilURI returns new OptNilURI with value set to v.
func NewOptNilURI(v url.URL) OptNilURI {
	return OptNilURI{
		Value: v,
		Set:   true,
	}
}

// OptNilURI is optional nullable url.URL.
type OptNilURI struct {
	Value url.URL
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilURI was set.
func (o OptNilURI) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilURI) Reset() {
	var v url.URL
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilURI) SetTo(v url.URL) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilURI) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilURI) SetToNull() {
	o.Set = true
	o.Null = true
	var v url.URL
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilURI) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilURI) Get() (v url.URL, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilURI) Or(d url.URL) url.URL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilUUID returns new OptNilUUID with value set to v.
func NewOptNilUUID(v uuid.UUID) OptNilUUID {
	return OptNilUUID{
		Value: v,
		Set:   true,
	}
}

// OptNilUUID is optional nullable uuid.UUID.
type OptNilUUID struct {
	Value uuid.UUID
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilUUID was set.
func (o OptNilUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilUUID) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilUUID) SetToNull() {
	o.Set = true
	o.Null = true
	var v uuid.UUID
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilUUID) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilUUID) Get() (v uuid.UUID, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptProgramWeek returns new OptProgramWeek with value set to v.
func NewOptProgramWeek(v ProgramWeek) OptProgramWeek {
	return OptProgramWeek{
		Value: v,
		Set:   true,
	}
}

// OptProgramWeek is optional ProgramWeek.
type OptProgramWeek struct {
	Value ProgramWeek
	Set   bool
}

// IsSet returns true if OptProgramWeek was set.
func (o OptProgramWeek) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptProgramWeek) Reset() {
	var v ProgramWeek
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptProgramWeek) SetTo(v ProgramWeek) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptProgramWeek) Get() (v ProgramWeek, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptProgramWeek) Or(d ProgramWeek) ProgramWeek {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUser returns new OptUser with value set to v.
func NewOptUser(v User) OptUser {
	return OptUser{
		Value: v,
		Set:   true,
	}
}

// OptUser is optional User.
type OptUser struct {
	Value User
	Set   bool
}

// IsSet returns true if OptUser was set.
func (o OptUser) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUser) Reset() {
	var v User
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUser) SetTo(v User) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUser) Get() (v User, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUser) Or(d User) User {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type Password string

// Ref: #/components/schemas/Prescription
type Prescription struct {
	SetsRepsText string        `json:"setsRepsText"`
	WeightKg     OptNilFloat64 `json:"weightKg"`
	WeightText   OptNilString  `json:"weightText"`
	RpeText      OptNilString  `json:"rpeText"`
	Unit         OptNilString  `json:"unit"`
}

// GetSetsRepsText returns the value of SetsRepsText.
func (s *Prescription) GetSetsRepsText() string {
	return s.SetsRepsText
}

// GetWeightKg returns the value of WeightKg.
func (s *Prescription) GetWeightKg() OptNilFloat64 {
	return s.WeightKg
}

// GetWeightText returns the value of WeightText.
func (s *Prescription) GetWeightText() OptNilString {
	return s.WeightText
}

// GetRpeText returns the value of RpeText.
func (s *Prescription) GetRpeText() OptNilString {
	return s.RpeText
}

// GetUnit returns the value of Unit.
func (s *Prescription) GetUnit() OptNilString {
	return s.Unit
}

// SetSetsRepsText sets the value of SetsRepsText.
func (s *Prescription) SetSetsRepsText(val string) {
	s.SetsRepsText = val
}

// SetWeightKg sets the value of WeightKg.
func (s *Prescription) SetWeightKg(val OptNilFloat64) {
	s.WeightKg = val
}

// SetWeightText sets the value of WeightText.
func (s *Prescription) SetWeightText(val OptNilString) {
	s.WeightText = val
}

// SetRpeText sets the value of RpeText.
func (s *Prescription) SetRpeText(val OptNilString) {
	s.RpeText = val
}

// SetUnit sets the value of Unit.
func (s *Prescription) SetUnit(val OptNilString) {
	s.Unit = val
}

// Ref: #/components/schemas/ProfileOneRepMaxes
type ProfileOneRepMaxes struct {
	Deadlift NilFloat64 `json:"deadlift"`
	Bench    NilFloat64 `json:"bench"`
	Squat    NilFloat64 `json:"squat"`
}

// GetDeadlift returns the value of Deadlift.
func (s *ProfileOneRepMaxes) GetDeadlift() NilFloat64 {
	return s.Deadlift
}

// GetBench returns the value of Bench.
func (s *ProfileOneRepMaxes) GetBench() NilFloat64 {
	return s.Bench
}

// GetSquat returns the value of Squat.
func (s *ProfileOneRepMaxes) GetSquat() NilFloat64 {
	return s.Squat
}

// SetDeadlift sets the value of Deadlift.
func (s *ProfileOneRepMaxes) SetDeadlift(val NilFloat64) {
	s.Deadlift = val
}

// SetBench sets the value of Bench.
func (s *ProfileOneRepMaxes) SetBench(val NilFloat64) {
	s.Bench = val
}

// SetSquat sets the value of Squat.
func (s *ProfileOneRepMaxes) SetSquat(val NilFloat64) {
	s.Squat = val
}

// Ref: #/components/schemas/ProgramCycle
type ProgramCycle struct {
	ID              uuid.UUID       `json:"id"`
	Title           string          `json:"title"`
	Status          CycleStatus     `json:"status"`
	CurrentWeek     ProgramWeek     `json:"currentWeek"`
	Settings        CycleSettings   `json:"settings"`
	ProgressSummary ProgressSummary `json:"progressSummary"`
	StartedAt       OptNilDateTime  `json:"startedAt"`
	CompletedAt     OptNilDateTime  `json:"completedAt"`
	CreatedAt       time.Time       `json:"createdAt"`
	UpdatedAt       time.Time       `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *ProgramCycle) GetID() uuid.UUID {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *ProgramCycle) GetTitle() string {
	return s.Title
}

// GetStatus returns the value of Status.
func (s *ProgramCycle) GetStatus() CycleStatus {
	return s.Status
}

// GetCurrentWeek returns the value of CurrentWeek.
func (s *ProgramCycle) GetCurrentWeek() ProgramWeek {
	return s.CurrentWeek
}

// GetSettings returns the value of Settings.
func (s *ProgramCycle) GetSettings() CycleSettings {
	return s.Settings
}

// GetProgressSummary returns the value of ProgressSummary.
func (s *ProgramCycle) GetProgressSummary() ProgressSummary {
	return s.ProgressSummary
}

// GetStartedAt returns the value of StartedAt.
func (s *ProgramCycle) GetStartedAt() OptNilDateTime {
	return s.StartedAt
}

// GetCompletedAt returns the value of CompletedAt.
func (s *ProgramCycle) GetCompletedAt() OptNilDateTime {
	return s.CompletedAt
}

// GetCreatedAt returns the value of CreatedAt.
func (s *ProgramCycle) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *ProgramCycle) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *ProgramCycle) SetID(val uuid.UUID) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *ProgramCycle) SetTitle(val string) {
	s.Title = val
}

// SetStatus sets the value of Status.
func (s *ProgramCycle) SetStatus(val CycleStatus) {
	s.Status = val
}

// SetCurrentWeek sets the value of CurrentWeek.
func (s *ProgramCycle) SetCurrentWeek(val ProgramWeek) {
	s.CurrentWeek = val
}

// SetSettings sets the value of Settings.
func (s *ProgramCycle) SetSettings(val CycleSettings) {
	s.Settings = val
}

// SetProgressSummary sets the value of ProgressSummary.
func (s *ProgramCycle) SetProgressSummary(val ProgressSummary) {
	s.ProgressSummary = val
}

// SetStartedAt sets the value of StartedAt.
func (s *ProgramCycle) SetStartedAt(val OptNilDateTime) {
	s.StartedAt = val
}

// SetCompletedAt sets the value of CompletedAt.
func (s *ProgramCycle) SetCompletedAt(val OptNilDateTime) {
	s.CompletedAt = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *ProgramCycle) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *ProgramCycle) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// Ref: #/components/schemas/ProgramOptionsResponse
type ProgramOptionsResponse struct {
	Weeks            []SelectOption    `json:"weeks"`
	Variants         []SelectOption    `json:"variants"`
	ProgressionSteps []SelectOption    `json:"progressionSteps"`
	Assistance       AssistanceOptions `json:"assistance"`
	Gpp              GPPOptions        `json:"gpp"`
}

// GetWeeks returns the value of Weeks.
func (s *ProgramOptionsResponse) GetWeeks() []SelectOption {
	return s.Weeks
}

// GetVariants returns the value of Variants.
func (s *ProgramOptionsResponse) GetVariants() []SelectOption {
	return s.Variants
}

// GetProgressionSteps returns the value of ProgressionSteps.
func (s *ProgramOptionsResponse) GetProgressionSteps() []SelectOption {
	return s.ProgressionSteps
}

// GetAssistance returns the value of Assistance.
func (s *ProgramOptionsResponse) GetAssistance() AssistanceOptions {
	return s.Assistance
}

// GetGpp returns the value of Gpp.
func (s *ProgramOptionsResponse) GetGpp() GPPOptions {
	return s.Gpp
}

// SetWeeks sets the value of Weeks.
func (s *ProgramOptionsResponse) SetWeeks(val []SelectOption) {
	s.Weeks = val
}

// SetVariants sets the value of Variants.
func (s *ProgramOptionsResponse) SetVariants(val []SelectOption) {
	s.Variants = val
}

// SetProgressionSteps sets the value of ProgressionSteps.
func (s *ProgramOptionsResponse) SetProgressionSteps(val []SelectOption) {
	s.ProgressionSteps = val
}

// SetAssistance sets the value of Assistance.
func (s *ProgramOptionsResponse) SetAssistance(val AssistanceOptions) {
	s.Assistance = val
}

// SetGpp sets the value of Gpp.
func (s *ProgramOptionsResponse) SetGpp(val GPPOptions) {
	s.Gpp = val
}

func (*ProgramOptionsResponse) getProgramOptionsRes() {}

// Ref: #/components/schemas/ProgramSelection
type ProgramSelection struct {
	Settings CycleSettings `json:"settings"`
	Week     ProgramWeek   `json:"week"`
}

// GetSettings returns the value of Settings.
func (s *ProgramSelection) GetSettings() CycleSettings {
	return s.Settings
}

// GetWeek returns the value of Week.
func (s *ProgramSelection) GetWeek() ProgramWeek {
	return s.Week
}

// SetSettings sets the value of Settings.
func (s *ProgramSelection) SetSettings(val CycleSettings) {
	s.Settings = val
}

// SetWeek sets the value of Week.
func (s *ProgramSelection) SetWeek(val ProgramWeek) {
	s.Week = val
}

// Ref: #/components/schemas/ProgramVariant
type ProgramVariant string

const (
	ProgramVariantVariant1 ProgramVariant = "variant_1"
	ProgramVariantVariant2 ProgramVariant = "variant_2"
)

// AllValues returns all ProgramVariant values.
func (ProgramVariant) AllValues() []ProgramVariant {
	return []ProgramVariant{
		ProgramVariantVariant1,
		ProgramVariantVariant2,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ProgramVariant) MarshalText() ([]byte, error) {
	switch s {
	case ProgramVariantVariant1:
		return []byte(s), nil
	case ProgramVariantVariant2:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ProgramVariant) UnmarshalText(data []byte) error {
	switch ProgramVariant(data) {
	case ProgramVariantVariant1:
		*s = ProgramVariantVariant1
		return nil
	case ProgramVariantVariant2:
		*s = ProgramVariantVariant2
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ProgramWeek
type ProgramWeek string

const (
	ProgramWeekWeek1 ProgramWeek = "week_1"
	ProgramWeekWeek2 ProgramWeek = "week_2"
	ProgramWeekWeek3 ProgramWeek = "week_3"
	ProgramWeekWeek4 ProgramWeek = "week_4"
	ProgramWeekWeek5 ProgramWeek = "week_5"
	ProgramWeekWeek6 ProgramWeek = "week_6"
	ProgramWeekWeek7 ProgramWeek = "week_7"
	ProgramWeekWeek8 ProgramWeek = "week_8"
)

// AllValues returns all ProgramWeek values.
func (ProgramWeek) AllValues() []ProgramWeek {
	return []ProgramWeek{
		ProgramWeekWeek1,
		ProgramWeekWeek2,
		ProgramWeekWeek3,
		ProgramWeekWeek4,
		ProgramWeekWeek5,
		ProgramWeekWeek6,
		ProgramWeekWeek7,
		ProgramWeekWeek8,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ProgramWeek) MarshalText() ([]byte, error) {
	switch s {
	case ProgramWeekWeek1:
		return []byte(s), nil
	case ProgramWeekWeek2:
		return []byte(s), nil
	case ProgramWeekWeek3:
		return []byte(s), nil
	case ProgramWeekWeek4:
		return []byte(s), nil
	case ProgramWeekWeek5:
		return []byte(s), nil
	case ProgramWeekWeek6:
		return []byte(s), nil
	case ProgramWeekWeek7:
		return []byte(s), nil
	case ProgramWeekWeek8:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ProgramWeek) UnmarshalText(data []byte) error {
	switch ProgramWeek(data) {
	case ProgramWeekWeek1:
		*s = ProgramWeekWeek1
		return nil
	case ProgramWeekWeek2:
		*s = ProgramWeekWeek2
		return nil
	case ProgramWeekWeek3:
		*s = ProgramWeekWeek3
		return nil
	case ProgramWeekWeek4:
		*s = ProgramWeekWeek4
		return nil
	case ProgramWeekWeek5:
		*s = ProgramWeekWeek5
		return nil
	case ProgramWeekWeek6:
		*s = ProgramWeekWeek6
		return nil
	case ProgramWeekWeek7:
		*s = ProgramWeekWeek7
		return nil
	case ProgramWeekWeek8:
		*s = ProgramWeekWeek8
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ProgressCheckpoint
type ProgressCheckpoint struct {
	ID          uuid.UUID                         `json:"id"`
	Week        ProgramWeek                       `json:"week"`
	DayId       ProgressCheckpointDayId           `json:"dayId"`
	ExerciseKey string                            `json:"exerciseKey"`
	RowKind     TrainingRowKind                   `json:"rowKind"`
	Status      CheckpointStatus                  `json:"status"`
	Prescribed  OptCheckpointPrescriptionSnapshot `json:"prescribed"`
	Completed   OptCheckpointCompletedData        `json:"completed"`
	Notes       OptNilString                      `json:"notes"`
	CompletedAt OptNilDateTime                    `json:"completedAt"`
	CreatedAt   time.Time                         `json:"createdAt"`
	UpdatedAt   time.Time                         `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *ProgressCheckpoint) GetID() uuid.UUID {
	return s.ID
}

// GetWeek returns the value of Week.
func (s *ProgressCheckpoint) GetWeek() ProgramWeek {
	return s.Week
}

// GetDayId returns the value of DayId.
func (s *ProgressCheckpoint) GetDayId() ProgressCheckpointDayId {
	return s.DayId
}

// GetExerciseKey returns the value of ExerciseKey.
func (s *ProgressCheckpoint) GetExerciseKey() string {
	return s.ExerciseKey
}

// GetRowKind returns the value of RowKind.
func (s *ProgressCheckpoint) GetRowKind() TrainingRowKind {
	return s.RowKind
}

// GetStatus returns the value of Status.
func (s *ProgressCheckpoint) GetStatus() CheckpointStatus {
	return s.Status
}

// GetPrescribed returns the value of Prescribed.
func (s *ProgressCheckpoint) GetPrescribed() OptCheckpointPrescriptionSnapshot {
	return s.Prescribed
}

// GetCompleted returns the value of Completed.
func (s *ProgressCheckpoint) GetCompleted() OptCheckpointCompletedData {
	return s.Completed
}

// GetNotes returns the value of Notes.
func (s *ProgressCheckpoint) GetNotes() OptNilString {
	return s.Notes
}

// GetCompletedAt returns the value of CompletedAt.
func (s *ProgressCheckpoint) GetCompletedAt() OptNilDateTime {
	return s.CompletedAt
}

// GetCreatedAt returns the value of CreatedAt.
func (s *ProgressCheckpoint) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *ProgressCheckpoint) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *ProgressCheckpoint) SetID(val uuid.UUID) {
	s.ID = val
}

// SetWeek sets the value of Week.
func (s *ProgressCheckpoint) SetWeek(val ProgramWeek) {
	s.Week = val
}

// SetDayId sets the value of DayId.
func (s *ProgressCheckpoint) SetDayId(val ProgressCheckpointDayId) {
	s.DayId = val
}

// SetExerciseKey sets the value of ExerciseKey.
func (s *ProgressCheckpoint) SetExerciseKey(val string) {
	s.ExerciseKey = val
}

// SetRowKind sets the value of RowKind.
func (s *ProgressCheckpoint) SetRowKind(val TrainingRowKind) {
	s.RowKind = val
}

// SetStatus sets the value of Status.
func (s *ProgressCheckpoint) SetStatus(val CheckpointStatus) {
	s.Status = val
}

// SetPrescribed sets the value of Prescribed.
func (s *ProgressCheckpoint) SetPrescribed(val OptCheckpointPrescriptionSnapshot) {
	s.Prescribed = val
}

// SetCompleted sets the value of Completed.
func (s *ProgressCheckpoint) SetCompleted(val OptCheckpointCompletedData) {
	s.Completed = val
}

// SetNotes sets the value of Notes.
func (s *ProgressCheckpoint) SetNotes(val OptNilString) {
	s.Notes = val
}

// SetCompletedAt sets the value of CompletedAt.
func (s *ProgressCheckpoint) SetCompletedAt(val OptNilDateTime) {
	s.CompletedAt = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *ProgressCheckpoint) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *ProgressCheckpoint) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

type ProgressCheckpointDayId string

const (
	ProgressCheckpointDayIdDay1 ProgressCheckpointDayId = "day_1"
	ProgressCheckpointDayIdDay2 ProgressCheckpointDayId = "day_2"
	ProgressCheckpointDayIdDay3 ProgressCheckpointDayId = "day_3"
)

// AllValues returns all ProgressCheckpointDayId values.
func (ProgressCheckpointDayId) AllValues() []ProgressCheckpointDayId {
	return []ProgressCheckpointDayId{
		ProgressCheckpointDayIdDay1,
		ProgressCheckpointDayIdDay2,
		ProgressCheckpointDayIdDay3,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ProgressCheckpointDayId) MarshalText() ([]byte, error) {
	switch s {
	case ProgressCheckpointDayIdDay1:
		return []byte(s), nil
	case ProgressCheckpointDayIdDay2:
		return []byte(s), nil
	case ProgressCheckpointDayIdDay3:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ProgressCheckpointDayId) UnmarshalText(data []byte) error {
	switch ProgressCheckpointDayId(data) {
	case ProgressCheckpointDayIdDay1:
		*s = ProgressCheckpointDayIdDay1
		return nil
	case ProgressCheckpointDayIdDay2:
		*s = ProgressCheckpointDayIdDay2
		return nil
	case ProgressCheckpointDayIdDay3:
		*s = ProgressCheckpointDayIdDay3
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ProgressCheckpointInput
type ProgressCheckpointInput struct {
	Week        ProgramWeek                       `json:"week"`
	DayId       ProgressCheckpointInputDayId      `json:"dayId"`
	ExerciseKey string                            `json:"exerciseKey"`
	RowKind     TrainingRowKind                   `json:"rowKind"`
	Status      CheckpointStatus                  `json:"status"`
	Prescribed  OptCheckpointPrescriptionSnapshot `json:"prescribed"`
	Completed   OptCheckpointCompletedData        `json:"completed"`
	Notes       OptNilString                      `json:"notes"`
	CompletedAt OptNilDateTime                    `json:"completedAt"`
}

// GetWeek returns the value of Week.
func (s *ProgressCheckpointInput) GetWeek() ProgramWeek {
	return s.Week
}

// GetDayId returns the value of DayId.
func (s *ProgressCheckpointInput) GetDayId() ProgressCheckpointInputDayId {
	return s.DayId
}

// GetExerciseKey returns the value of ExerciseKey.
func (s *ProgressCheckpointInput) GetExerciseKey() string {
	return s.ExerciseKey
}

// GetRowKind returns the value of RowKind.
func (s *ProgressCheckpointInput) GetRowKind() TrainingRowKind {
	return s.RowKind
}

// GetStatus returns the value of Status.
func (s *ProgressCheckpointInput) GetStatus() CheckpointStatus {
	return s.Status
}

// GetPrescribed returns the value of Prescribed.
func (s *ProgressCheckpointInput) GetPrescribed() OptCheckpointPrescriptionSnapshot {
	return s.Prescribed
}

// GetCompleted returns the value of Completed.
func (s *ProgressCheckpointInput) GetCompleted() OptCheckpointCompletedData {
	return s.Completed
}

// GetNotes returns the value of Notes.
func (s *ProgressCheckpointInput) GetNotes() OptNilString {
	return s.Notes
}

// GetCompletedAt returns the value of CompletedAt.
func (s *ProgressCheckpointInput) GetCompletedAt() OptNilDateTime {
	return s.CompletedAt
}

// SetWeek sets the value of Week.
func (s *ProgressCheckpointInput) SetWeek(val ProgramWeek) {
	s.Week = val
}

// SetDayId sets the value of DayId.
func (s *ProgressCheckpointInput) SetDayId(val ProgressCheckpointInputDayId) {
	s.DayId = val
}

// SetExerciseKey sets the value of ExerciseKey.
func (s *ProgressCheckpointInput) SetExerciseKey(val string) {
	s.ExerciseKey = val
}

// SetRowKind sets the value of RowKind.
func (s *ProgressCheckpointInput) SetRowKind(val TrainingRowKind) {
	s.RowKind = val
}

// SetStatus sets the value of Status.
func (s *ProgressCheckpointInput) SetStatus(val CheckpointStatus) {
	s.Status = val
}

// SetPrescribed sets the value of Prescribed.
func (s *ProgressCheckpointInput) SetPrescribed(val OptCheckpointPrescriptionSnapshot) {
	s.Prescribed = val
}

// SetCompleted sets the value of Completed.
func (s *ProgressCheckpointInput) SetCompleted(val OptCheckpointCompletedData) {
	s.Completed = val
}

// SetNotes sets the value of Notes.
func (s *ProgressCheckpointInput) SetNotes(val OptNilString) {
	s.Notes = val
}

// SetCompletedAt sets the value of CompletedAt.
func (s *ProgressCheckpointInput) SetCompletedAt(val OptNilDateTime) {
	s.CompletedAt = val
}

type ProgressCheckpointInputDayId string

const (
	ProgressCheckpointInputDayIdDay1 ProgressCheckpointInputDayId = "day_1"
	ProgressCheckpointInputDayIdDay2 ProgressCheckpointInputDayId = "day_2"
	ProgressCheckpointInputDayIdDay3 ProgressCheckpointInputDayId = "day_3"
)

// AllValues returns all ProgressCheckpointInputDayId values.
func (ProgressCheckpointInputDayId) AllValues() []ProgressCheckpointInputDayId {
	return []ProgressCheckpointInputDayId{
		ProgressCheckpointInputDayIdDay1,
		ProgressCheckpointInputDayIdDay2,
		ProgressCheckpointInputDayIdDay3,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ProgressCheckpointInputDayId) MarshalText() ([]byte, error) {
	switch s {
	case ProgressCheckpointInputDayIdDay1:
		return []byte(s), nil
	case ProgressCheckpointInputDayIdDay2:
		return []byte(s), nil
	case ProgressCheckpointInputDayIdDay3:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ProgressCheckpointInputDayId) UnmarshalText(data []byte) error {
	switch ProgressCheckpointInputDayId(data) {
	case ProgressCheckpointInputDayIdDay1:
		*s = ProgressCheckpointInputDayIdDay1
		return nil
	case ProgressCheckpointInputDayIdDay2:
		*s = ProgressCheckpointInputDayIdDay2
		return nil
	case ProgressCheckpointInputDayIdDay3:
		*s = ProgressCheckpointInputDayIdDay3
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ProgressCheckpointResponse
type ProgressCheckpointResponse struct {
	Checkpoint ProgressCheckpoint `json:"checkpoint"`
}

// GetCheckpoint returns the value of Checkpoint.
func (s *ProgressCheckpointResponse) GetCheckpoint() ProgressCheckpoint {
	return s.Checkpoint
}

// SetCheckpoint sets the value of Checkpoint.
func (s *ProgressCheckpointResponse) SetCheckpoint(val ProgressCheckpoint) {
	s.Checkpoint = val
}

func (*ProgressCheckpointResponse) upsertCurrentCycleCheckpointRes() {}

// Ref: #/components/schemas/ProgressCheckpointsResponse
type ProgressCheckpointsResponse struct {
	Items []ProgressCheckpoint `json:"items"`
}

// GetItems returns the value of Items.
func (s *ProgressCheckpointsResponse) GetItems() []ProgressCheckpoint {
	return s.Items
}

// SetItems sets the value of Items.
func (s *ProgressCheckpointsResponse) SetItems(val []ProgressCheckpoint) {
	s.Items = val
}

func (*ProgressCheckpointsResponse) listCurrentCycleProgressRes() {}

// Ref: #/components/schemas/ProgressSummary
type ProgressSummary struct {
	Done    int `json:"done"`
	Partial int `json:"partial"`
	Skipped int `json:"skipped"`
	Planned int `json:"planned"`
}

// GetDone returns the value of Done.
func (s *ProgressSummary) GetDone() int {
	return s.Done
}

// GetPartial returns the value of Partial.
func (s *ProgressSummary) GetPartial() int {
	return s.Partial
}

// GetSkipped returns the value of Skipped.
func (s *ProgressSummary) GetSkipped() int {
	return s.Skipped
}

// GetPlanned returns the value of Planned.
func (s *ProgressSummary) GetPlanned() int {
	return s.Planned
}

// SetDone sets the value of Done.
func (s *ProgressSummary) SetDone(val int) {
	s.Done = val
}

// SetPartial sets the value of Partial.
func (s *ProgressSummary) SetPartial(val int) {
	s.Partial = val
}

// SetSkipped sets the value of Skipped.
func (s *ProgressSummary) SetSkipped(val int) {
	s.Skipped = val
}

// SetPlanned sets the value of Planned.
func (s *ProgressSummary) SetPlanned(val int) {
	s.Planned = val
}

// Main-lift progression step. `step_4_percent` matches the current XLSX behavior. `step_5_percent` is
// an explicit user/program preference, not automatic for `variant_2`.
// Ref: #/components/schemas/ProgressionStep
type ProgressionStep string

const (
	ProgressionStepStep4Percent ProgressionStep = "step_4_percent"
	ProgressionStepStep5Percent ProgressionStep = "step_5_percent"
)

// AllValues returns all ProgressionStep values.
func (ProgressionStep) AllValues() []ProgressionStep {
	return []ProgressionStep{
		ProgressionStepStep4Percent,
		ProgressionStepStep5Percent,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ProgressionStep) MarshalText() ([]byte, error) {
	switch s {
	case ProgressionStepStep4Percent:
		return []byte(s), nil
	case ProgressionStepStep5Percent:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ProgressionStep) UnmarshalText(data []byte) error {
	switch ProgressionStep(data) {
	case ProgressionStepStep4Percent:
		*s = ProgressionStepStep4Percent
		return nil
	case ProgressionStepStep5Percent:
		*s = ProgressionStepStep5Percent
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/PutAthleteProfileRequest
type PutAthleteProfileRequest struct {
	Profile AthleteProfileInput `json:"profile"`
}

// GetProfile returns the value of Profile.
func (s *PutAthleteProfileRequest) GetProfile() AthleteProfileInput {
	return s.Profile
}

// SetProfile sets the value of Profile.
func (s *PutAthleteProfileRequest) SetProfile(val AthleteProfileInput) {
	s.Profile = val
}

type PutCurrentCycleBadRequest ErrorResponse

func (*PutCurrentCycleBadRequest) putCurrentCycleRes() {}

// Ref: #/components/schemas/PutCurrentCycleRequest
type PutCurrentCycleRequest struct {
	Title        string        `json:"title"`
	CurrentWeek  ProgramWeek   `json:"currentWeek"`
	Settings     CycleSettings `json:"settings"`
	ChangeReason OptNilString  `json:"changeReason"`
}

// GetTitle returns the value of Title.
func (s *PutCurrentCycleRequest) GetTitle() string {
	return s.Title
}

// GetCurrentWeek returns the value of CurrentWeek.
func (s *PutCurrentCycleRequest) GetCurrentWeek() ProgramWeek {
	return s.CurrentWeek
}

// GetSettings returns the value of Settings.
func (s *PutCurrentCycleRequest) GetSettings() CycleSettings {
	return s.Settings
}

// GetChangeReason returns the value of ChangeReason.
func (s *PutCurrentCycleRequest) GetChangeReason() OptNilString {
	return s.ChangeReason
}

// SetTitle sets the value of Title.
func (s *PutCurrentCycleRequest) SetTitle(val string) {
	s.Title = val
}

// SetCurrentWeek sets the value of CurrentWeek.
func (s *PutCurrentCycleRequest) SetCurrentWeek(val ProgramWeek) {
	s.CurrentWeek = val
}

// SetSettings sets the value of Settings.
func (s *PutCurrentCycleRequest) SetSettings(val CycleSettings) {
	s.Settings = val
}

// SetChangeReason sets the value of ChangeReason.
func (s *PutCurrentCycleRequest) SetChangeReason(val OptNilString) {
	s.ChangeReason = val
}

type PutCurrentCycleUnauthorized ErrorResponse

func (*PutCurrentCycleUnauthorized) putCurrentCycleRes() {}

type PutCycleBadRequest ErrorResponse

func (*PutCycleBadRequest) putCycleRes() {}

type PutCycleNotFound ErrorResponse

func (*PutCycleNotFound) putCycleRes() {}

type PutCycleUnauthorized ErrorResponse

func (*PutCycleUnauthorized) putCycleRes() {}

type PutMyProfileBadRequest ErrorResponse

func (*PutMyProfileBadRequest) putMyProfileRes() {}

type PutMyProfileUnauthorized ErrorResponse

func (*PutMyProfileUnauthorized) putMyProfileRes() {}

type RegisterBadRequest ErrorResponse

func (*RegisterBadRequest) registerRes() {}

type RegisterConflict ErrorResponse

func (*RegisterConflict) registerRes() {}

// Ref: #/components/schemas/RegisterRequest
type RegisterRequest struct {
	Nickname Nickname `json:"nickname"`
	Password Password `json:"password"`
}

// GetNickname returns the value of Nickname.
func (s *RegisterRequest) GetNickname() Nickname {
	return s.Nickname
}

// GetPassword returns the value of Password.
func (s *RegisterRequest) GetPassword() Password {
	return s.Password
}

// SetNickname sets the value of Nickname.
func (s *RegisterRequest) SetNickname(val Nickname) {
	s.Nickname = val
}

// SetPassword sets the value of Password.
func (s *RegisterRequest) SetPassword(val Password) {
	s.Password = val
}

// Ref: #/components/schemas/SelectOption
type SelectOption struct {
	ID    string `json:"id"`
	Label string `json:"label"`
}

// GetID returns the value of ID.
func (s *SelectOption) GetID() string {
	return s.ID
}

// GetLabel returns the value of Label.
func (s *SelectOption) GetLabel() string {
	return s.Label
}

// SetID sets the value of ID.
func (s *SelectOption) SetID(val string) {
	s.ID = val
}

// SetLabel sets the value of Label.
func (s *SelectOption) SetLabel(val string) {
	s.Label = val
}

// Ref: #/components/schemas/ServiceInfo
type ServiceInfo struct {
	AuthMode    string `json:"authMode"`
	HasDatabase bool   `json:"hasDatabase"`
}

// GetAuthMode returns the value of AuthMode.
func (s *ServiceInfo) GetAuthMode() string {
	return s.AuthMode
}

// GetHasDatabase returns the value of HasDatabase.
func (s *ServiceInfo) GetHasDatabase() bool {
	return s.HasDatabase
}

// SetAuthMode sets the value of AuthMode.
func (s *ServiceInfo) SetAuthMode(val string) {
	s.AuthMode = val
}

// SetHasDatabase sets the value of HasDatabase.
func (s *ServiceInfo) SetHasDatabase(val bool) {
	s.HasDatabase = val
}

type SessionCookie struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *SessionCookie) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *SessionCookie) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *SessionCookie) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *SessionCookie) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/SessionResponse
type SessionResponse struct {
	Authenticated bool    `json:"authenticated"`
	User          OptUser `json:"user"`
}

// GetAuthenticated returns the value of Authenticated.
func (s *SessionResponse) GetAuthenticated() bool {
	return s.Authenticated
}

// GetUser returns the value of User.
func (s *SessionResponse) GetUser() OptUser {
	return s.User
}

// SetAuthenticated sets the value of Authenticated.
func (s *SessionResponse) SetAuthenticated(val bool) {
	s.Authenticated = val
}

// SetUser sets the value of User.
func (s *SessionResponse) SetUser(val OptUser) {
	s.User = val
}

// Ref: #/components/schemas/TrainingDay
type TrainingDay struct {
	ID    TrainingDayID `json:"id"`
	Label string        `json:"label"`
	Focus string        `json:"focus"`
	Rows  []TrainingRow `json:"rows"`
}

// GetID returns the value of ID.
func (s *TrainingDay) GetID() TrainingDayID {
	return s.ID
}

// GetLabel returns the value of Label.
func (s *TrainingDay) GetLabel() string {
	return s.Label
}

// GetFocus returns the value of Focus.
func (s *TrainingDay) GetFocus() string {
	return s.Focus
}

// GetRows returns the value of Rows.
func (s *TrainingDay) GetRows() []TrainingRow {
	return s.Rows
}

// SetID sets the value of ID.
func (s *TrainingDay) SetID(val TrainingDayID) {
	s.ID = val
}

// SetLabel sets the value of Label.
func (s *TrainingDay) SetLabel(val string) {
	s.Label = val
}

// SetFocus sets the value of Focus.
func (s *TrainingDay) SetFocus(val string) {
	s.Focus = val
}

// SetRows sets the value of Rows.
func (s *TrainingDay) SetRows(val []TrainingRow) {
	s.Rows = val
}

type TrainingDayID string

const (
	TrainingDayIDDay1 TrainingDayID = "day_1"
	TrainingDayIDDay2 TrainingDayID = "day_2"
	TrainingDayIDDay3 TrainingDayID = "day_3"
)

// AllValues returns all TrainingDayID values.
func (TrainingDayID) AllValues() []TrainingDayID {
	return []TrainingDayID{
		TrainingDayIDDay1,
		TrainingDayIDDay2,
		TrainingDayIDDay3,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s TrainingDayID) MarshalText() ([]byte, error) {
	switch s {
	case TrainingDayIDDay1:
		return []byte(s), nil
	case TrainingDayIDDay2:
		return []byte(s), nil
	case TrainingDayIDDay3:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *TrainingDayID) UnmarshalText(data []byte) error {
	switch TrainingDayID(data) {
	case TrainingDayIDDay1:
		*s = TrainingDayIDDay1
		return nil
	case TrainingDayIDDay2:
		*s = TrainingDayIDDay2
		return nil
	case TrainingDayIDDay3:
		*s = TrainingDayIDDay3
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/TrainingPlanResponse
type TrainingPlanResponse struct {
	Selection      ProgramSelection `json:"selection"`
	Days           []TrainingDay    `json:"days"`
	FormulaVersion string           `json:"formulaVersion"`
	Warnings       []string         `json:"warnings"`
}

// GetSelection returns the value of Selection.
func (s *TrainingPlanResponse) GetSelection() ProgramSelection {
	return s.Selection
}

// GetDays returns the value of Days.
func (s *TrainingPlanResponse) GetDays() []TrainingDay {
	return s.Days
}

// GetFormulaVersion returns the value of FormulaVersion.
func (s *TrainingPlanResponse) GetFormulaVersion() string {
	return s.FormulaVersion
}

// GetWarnings returns the value of Warnings.
func (s *TrainingPlanResponse) GetWarnings() []string {
	return s.Warnings
}

// SetSelection sets the value of Selection.
func (s *TrainingPlanResponse) SetSelection(val ProgramSelection) {
	s.Selection = val
}

// SetDays sets the value of Days.
func (s *TrainingPlanResponse) SetDays(val []TrainingDay) {
	s.Days = val
}

// SetFormulaVersion sets the value of FormulaVersion.
func (s *TrainingPlanResponse) SetFormulaVersion(val string) {
	s.FormulaVersion = val
}

// SetWarnings sets the value of Warnings.
func (s *TrainingPlanResponse) SetWarnings(val []string) {
	s.Warnings = val
}

func (*TrainingPlanResponse) calculateProgramRes()    {}
func (*TrainingPlanResponse) getCurrentCyclePlanRes() {}

// Ref: #/components/schemas/TrainingRow
type TrainingRow struct {
	RowId        string          `json:"rowId"`
	ExerciseKey  string          `json:"exerciseKey"`
	ExerciseName string          `json:"exerciseName"`
	Kind         TrainingRowKind `json:"kind"`
	Prescription Prescription    `json:"prescription"`
}

// GetRowId returns the value of RowId.
func (s *TrainingRow) GetRowId() string {
	return s.RowId
}

// GetExerciseKey returns the value of ExerciseKey.
func (s *TrainingRow) GetExerciseKey() string {
	return s.ExerciseKey
}

// GetExerciseName returns the value of ExerciseName.
func (s *TrainingRow) GetExerciseName() string {
	return s.ExerciseName
}

// GetKind returns the value of Kind.
func (s *TrainingRow) GetKind() TrainingRowKind {
	return s.Kind
}

// GetPrescription returns the value of Prescription.
func (s *TrainingRow) GetPrescription() Prescription {
	return s.Prescription
}

// SetRowId sets the value of RowId.
func (s *TrainingRow) SetRowId(val string) {
	s.RowId = val
}

// SetExerciseKey sets the value of ExerciseKey.
func (s *TrainingRow) SetExerciseKey(val string) {
	s.ExerciseKey = val
}

// SetExerciseName sets the value of ExerciseName.
func (s *TrainingRow) SetExerciseName(val string) {
	s.ExerciseName = val
}

// SetKind sets the value of Kind.
func (s *TrainingRow) SetKind(val TrainingRowKind) {
	s.Kind = val
}

// SetPrescription sets the value of Prescription.
func (s *TrainingRow) SetPrescription(val Prescription) {
	s.Prescription = val
}

// Ref: #/components/schemas/TrainingRowKind
type TrainingRowKind string

const (
	TrainingRowKindMain       TrainingRowKind = "main"
	TrainingRowKindLight      TrainingRowKind = "light"
	TrainingRowKindAssistance TrainingRowKind = "assistance"
	TrainingRowKindGpp        TrainingRowKind = "gpp"
)

// AllValues returns all TrainingRowKind values.
func (TrainingRowKind) AllValues() []TrainingRowKind {
	return []TrainingRowKind{
		TrainingRowKindMain,
		TrainingRowKindLight,
		TrainingRowKindAssistance,
		TrainingRowKindGpp,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s TrainingRowKind) MarshalText() ([]byte, error) {
	switch s {
	case TrainingRowKindMain:
		return []byte(s), nil
	case TrainingRowKindLight:
		return []byte(s), nil
	case TrainingRowKindAssistance:
		return []byte(s), nil
	case TrainingRowKindGpp:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *TrainingRowKind) UnmarshalText(data []byte) error {
	switch TrainingRowKind(data) {
	case TrainingRowKindMain:
		*s = TrainingRowKindMain
		return nil
	case TrainingRowKindLight:
		*s = TrainingRowKindLight
		return nil
	case TrainingRowKindAssistance:
		*s = TrainingRowKindAssistance
		return nil
	case TrainingRowKindGpp:
		*s = TrainingRowKindGpp
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type UpsertCurrentCycleCheckpointBadRequest ErrorResponse

func (*UpsertCurrentCycleCheckpointBadRequest) upsertCurrentCycleCheckpointRes() {}

type UpsertCurrentCycleCheckpointNotFound ErrorResponse

func (*UpsertCurrentCycleCheckpointNotFound) upsertCurrentCycleCheckpointRes() {}

type UpsertCurrentCycleCheckpointUnauthorized ErrorResponse

func (*UpsertCurrentCycleCheckpointUnauthorized) upsertCurrentCycleCheckpointRes() {}

// Ref: #/components/schemas/UpsertProgressCheckpointRequest
type UpsertProgressCheckpointRequest struct {
	Checkpoint ProgressCheckpointInput `json:"checkpoint"`
}

// GetCheckpoint returns the value of Checkpoint.
func (s *UpsertProgressCheckpointRequest) GetCheckpoint() ProgressCheckpointInput {
	return s.Checkpoint
}

// SetCheckpoint sets the value of Checkpoint.
func (s *UpsertProgressCheckpointRequest) SetCheckpoint(val ProgressCheckpointInput) {
	s.Checkpoint = val
}

// Ref: #/components/schemas/User
type User struct {
	ID        uuid.UUID `json:"id"`
	Nickname  Nickname  `json:"nickname"`
	CreatedAt time.Time `json:"createdAt"`
}

// GetID returns the value of ID.
func (s *User) GetID() uuid.UUID {
	return s.ID
}

// GetNickname returns the value of Nickname.
func (s *User) GetNickname() Nickname {
	return s.Nickname
}

// GetCreatedAt returns the value of CreatedAt.
func (s *User) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// SetID sets the value of ID.
func (s *User) SetID(val uuid.UUID) {
	s.ID = val
}

// SetNickname sets the value of Nickname.
func (s *User) SetNickname(val Nickname) {
	s.Nickname = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *User) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}
