// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	ActivateCycleOperation                OperationName = "ActivateCycle"
	AdvanceCurrentCycleOperation          OperationName = "AdvanceCurrentCycle"
	BootstrapOperation                    OperationName = "Bootstrap"
	CalculateProgramOperation             OperationName = "CalculateProgram"
	CreateCycleOperation                  OperationName = "CreateCycle"
	DeleteCurrentCycleCheckpointOperation OperationName = "DeleteCurrentCycleCheckpoint"
	GetAuthSessionOperation               OperationName = "GetAuthSession"
	GetCatalogExerciseOperation           OperationName = "GetCatalogExercise"
	GetCurrentCycleOperation              OperationName = "GetCurrentCycle"
	GetCurrentCyclePlanOperation          OperationName = "GetCurrentCyclePlan"
	GetExerciseDetailsOperation           OperationName = "GetExerciseDetails"
	GetMeOperation                        OperationName = "GetMe"
	GetMyProfileOperation                 OperationName = "GetMyProfile"
	GetProgramOptionsOperation            OperationName = "GetProgramOptions"
	HealthzOperation                      OperationName = "Healthz"
	ListCurrentCycleProgressOperation     OperationName = "ListCurrentCycleProgress"
	ListCyclesOperation                   OperationName = "ListCycles"
	ListExercisesOperation                OperationName = "ListExercises"
	LoginOperation                        OperationName = "Login"
	LogoutOperation                       OperationName = "Logout"
	PutCurrentCycleOperation              OperationName = "PutCurrentCycle"
	PutCycleOperation                     OperationName = "PutCycle"
	PutMyProfileOperation                 OperationName = "PutMyProfile"
	RegisterOperation                     OperationName = "Register"
	UpsertCurrentCycleCheckpointOperation OperationName = "UpsertCurrentCycleCheckpoint"
)
