// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// DeleteCurrentCycleCheckpointParams is parameters of deleteCurrentCycleCheckpoint operation.
type DeleteCurrentCycleCheckpointParams struct {
	CheckpointId uuid.UUID
}

func unpackDeleteCurrentCycleCheckpointParams(packed middleware.Parameters) (params DeleteCurrentCycleCheckpointParams) {
	{
		key := middleware.ParameterKey{
			Name: "checkpointId",
			In:   "path",
		}
		params.CheckpointId = packed[key].(uuid.UUID)
	}
	return params
}

func decodeDeleteCurrentCycleCheckpointParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteCurrentCycleCheckpointParams, _ error) {
	// Decode path: checkpointId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "checkpointId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.CheckpointId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "checkpointId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetExerciseDetailsParams is parameters of getExerciseDetails operation.
type GetExerciseDetailsParams struct {
	ExerciseKey string
}

func unpackGetExerciseDetailsParams(packed middleware.Parameters) (params GetExerciseDetailsParams) {
	{
		key := middleware.ParameterKey{
			Name: "exerciseKey",
			In:   "path",
		}
		params.ExerciseKey = packed[key].(string)
	}
	return params
}

func decodeGetExerciseDetailsParams(args [1]string, argsEscaped bool, r *http.Request) (params GetExerciseDetailsParams, _ error) {
	// Decode path: exerciseKey.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "exerciseKey",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ExerciseKey = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.ExerciseKey)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "exerciseKey",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ListCurrentCycleProgressParams is parameters of listCurrentCycleProgress operation.
type ListCurrentCycleProgressParams struct {
	Week OptProgramWeek `json:",omitempty,omitzero"`
}

func unpackListCurrentCycleProgressParams(packed middleware.Parameters) (params ListCurrentCycleProgressParams) {
	{
		key := middleware.ParameterKey{
			Name: "week",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Week = v.(OptProgramWeek)
		}
	}
	return params
}

func decodeListCurrentCycleProgressParams(args [0]string, argsEscaped bool, r *http.Request) (params ListCurrentCycleProgressParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: week.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "week",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotWeekVal ProgramWeek
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotWeekVal = ProgramWeek(c)
					return nil
				}(); err != nil {
					return err
				}
				params.Week.SetTo(paramsDotWeekVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if value, ok := params.Week.Get(); ok {
					if err := func() error {
						if err := value.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						return err
					}
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "week",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
