// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AdvanceCurrentCycle implements advanceCurrentCycle operation.
	//
	// Move the current cycle to another week.
	//
	// POST /v1/cycles/current/advance
	AdvanceCurrentCycle(ctx context.Context, req *AdvanceCycleRequest) (AdvanceCurrentCycleRes, error)
	// Bootstrap implements bootstrap operation.
	//
	// Sets `init=1`. This cookie is not auth.
	//
	// GET /v1/bootstrap
	Bootstrap(ctx context.Context) (*BootstrapResponseHeaders, error)
	// CalculateProgram implements calculateProgram operation.
	//
	// Calculate training days from settings and week.
	//
	// POST /v1/program/calculate
	CalculateProgram(ctx context.Context, req *CalculateProgramRequest) (CalculateProgramRes, error)
	// DeleteCurrentCycleCheckpoint implements deleteCurrentCycleCheckpoint operation.
	//
	// Delete one progress checkpoint.
	//
	// DELETE /v1/cycles/current/progress/checkpoints/{checkpointId}
	DeleteCurrentCycleCheckpoint(ctx context.Context, params DeleteCurrentCycleCheckpointParams) (DeleteCurrentCycleCheckpointRes, error)
	// GetCurrentCycle implements getCurrentCycle operation.
	//
	// Get current active cycle with editable settings.
	//
	// GET /v1/cycles/current
	GetCurrentCycle(ctx context.Context) (GetCurrentCycleRes, error)
	// GetExerciseDetails implements getExerciseDetails operation.
	//
	// Get details for a program exercise.
	//
	// GET /v1/exercises/{exerciseKey}
	GetExerciseDetails(ctx context.Context, params GetExerciseDetailsParams) (GetExerciseDetailsRes, error)
	// GetMe implements getMe operation.
	//
	// Get current authenticated user.
	//
	// GET /v1/me
	GetMe(ctx context.Context) (GetMeRes, error)
	// GetMyProfile implements getMyProfile operation.
	//
	// Get athlete profile defaults.
	//
	// GET /v1/me/profile
	GetMyProfile(ctx context.Context) (GetMyProfileRes, error)
	// GetProgramOptions implements getProgramOptions operation.
	//
	// Get selectable program options.
	//
	// GET /v1/program/options
	GetProgramOptions(ctx context.Context) (*ProgramOptionsResponse, error)
	// Healthz implements healthz operation.
	//
	// Health check.
	//
	// GET /healthz
	Healthz(ctx context.Context) (*HealthResponse, error)
	// ListCurrentCycleProgress implements listCurrentCycleProgress operation.
	//
	// List checkpoints for the current active cycle.
	//
	// GET /v1/cycles/current/progress
	ListCurrentCycleProgress(ctx context.Context, params ListCurrentCycleProgressParams) (ListCurrentCycleProgressRes, error)
	// Login implements login operation.
	//
	// Sign in with nickname and password.
	//
	// POST /v1/auth/login
	Login(ctx context.Context, req *LoginRequest) (LoginRes, error)
	// Logout implements logout operation.
	//
	// Revoke current session.
	//
	// POST /v1/auth/logout
	Logout(ctx context.Context) (LogoutRes, error)
	// PutCurrentCycle implements putCurrentCycle operation.
	//
	// Settings may be changed while progressing through the cycle.
	//
	// PUT /v1/cycles/current
	PutCurrentCycle(ctx context.Context, req *PutCurrentCycleRequest) (PutCurrentCycleRes, error)
	// PutMyProfile implements putMyProfile operation.
	//
	// Profile changes do not automatically rewrite existing cycle settings.
	//
	// PUT /v1/me/profile
	PutMyProfile(ctx context.Context, req *PutAthleteProfileRequest) (PutMyProfileRes, error)
	// Register implements register operation.
	//
	// Create a local user.
	//
	// POST /v1/auth/register
	Register(ctx context.Context, req *RegisterRequest) (RegisterRes, error)
	// UpsertCurrentCycleCheckpoint implements upsertCurrentCycleCheckpoint operation.
	//
	// Upserts by `(cycle, week, dayId, exerciseKey)` for the MVP.
	//
	// PUT /v1/cycles/current/progress/checkpoints
	UpsertCurrentCycleCheckpoint(ctx context.Context, req *UpsertProgressCheckpointRequest) (UpsertCurrentCycleCheckpointRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
