// Code generated by ogen, DO NOT EDIT.
package api

type AdvanceCurrentCycleRes interface {
	advanceCurrentCycleRes()
}

type CalculateProgramRes interface {
	calculateProgramRes()
}

type DeleteCurrentCycleCheckpointRes interface {
	deleteCurrentCycleCheckpointRes()
}

type GetCurrentCycleRes interface {
	getCurrentCycleRes()
}

type GetExerciseDetailsRes interface {
	getExerciseDetailsRes()
}

type GetMeRes interface {
	getMeRes()
}

type GetMyProfileRes interface {
	getMyProfileRes()
}

type ListCurrentCycleProgressRes interface {
	listCurrentCycleProgressRes()
}

type LoginRes interface {
	loginRes()
}

type LogoutRes interface {
	logoutRes()
}

type PutCurrentCycleRes interface {
	putCurrentCycleRes()
}

type PutMyProfileRes interface {
	putMyProfileRes()
}

type RegisterRes interface {
	registerRes()
}

type UpsertCurrentCycleCheckpointRes interface {
	upsertCurrentCycleCheckpointRes()
}
