// Code generated by ogen, DO NOT EDIT.
package api

type ActivateCycleRes interface {
	activateCycleRes()
}

type AdvanceCurrentCycleRes interface {
	advanceCurrentCycleRes()
}

type CalculateProgramRes interface {
	calculateProgramRes()
}

type CreateCycleRes interface {
	createCycleRes()
}

type DeleteCurrentCycleCheckpointRes interface {
	deleteCurrentCycleCheckpointRes()
}

type GetCatalogExerciseRes interface {
	getCatalogExerciseRes()
}

type GetCurrentCyclePlanRes interface {
	getCurrentCyclePlanRes()
}

type GetCurrentCycleRes interface {
	getCurrentCycleRes()
}

type GetExerciseDetailsRes interface {
	getExerciseDetailsRes()
}

type GetMeRes interface {
	getMeRes()
}

type GetMyProfileRes interface {
	getMyProfileRes()
}

type GetProgramOptionsRes interface {
	getProgramOptionsRes()
}

type ListCurrentCycleProgressRes interface {
	listCurrentCycleProgressRes()
}

type ListCyclesRes interface {
	listCyclesRes()
}

type ListExercisesRes interface {
	listExercisesRes()
}

type LoginRes interface {
	loginRes()
}

type LogoutRes interface {
	logoutRes()
}

type PutCurrentCycleRes interface {
	putCurrentCycleRes()
}

type PutCycleRes interface {
	putCycleRes()
}

type PutMyProfileRes interface {
	putMyProfileRes()
}

type RegisterRes interface {
	registerRes()
}

type UpsertCurrentCycleCheckpointRes interface {
	upsertCurrentCycleCheckpointRes()
}
